### PR TITLE
Add option of existingType to .enum method to support repeated use of enums

### PR DESCRIPTION
**Pull request by ekeric13**
I was super happy to see knex supporting native enums in postgres, but when I had an enum that I used repeatedly across different columns in different tables, I was running into errors as the `enum` method created the type enum for you each time. The type would already exist so it would error. I only wanted to create the type once, afterwards I just wanted to use that enum.

Could we add a flag in the options param to not run the sql that creates the type enum?

The first time you run it you could do

```
table.enu('current_mood', ['sad', 'ok', 'happy'], { useNative: true, enumName: 'mood' })
```

And then the other times you can run

```
table.enu('mood', ['sad', 'ok', 'happy'], { useNative: true, enumName: 'mood', existingType: true })
```

### CODE REVIEW

**Comment by heisian** [comment]
I second this proposition and motion for a move to merge :P

**Comment by elhigu** [comment]
Sounds reasonable, I cannot think any better API for handling this situation.

**Comment by kibertoad** [comment]
@ekeric13 Would you consider finishing this PR?

**Comment by ekeric13** [comment]
Yeah for sure. @heisian 	and I have a working implementation, just need to write tests for it.

**Comment by kibertoad** [comment]
Awesome! Also PR for documentation in https://github.com/knex/documentation would be most appreciated :)

**Comment by kibertoad** [comment]
@ekeric13 Thank you very much! It's 0:30 here already, it was a long day; I'll take a look at it tomorrow and comment ASAP, sorry for the delay.

**Comment by ekeric13** [comment]
So what is the process after this? Just will be merged in for the next release?

**Comment by kibertoad** [comment]
@ekeric13 Probably can be merged within 0.16.0 window, but before that I assume we should consider the alternative improved syntax that you've suggested?..

**Comment by kibertoad** [comment]
@ekeric13 Looked at previous and current syntax and I think that it makes perfect sense, would you do the change?

**Comment by ekeric13** [comment]
Okay, added the proposed ternary operator to make the function type agnostic of the values in the case where the values aren't being used.

Updated the docs as well for further clarification:
https://github.com/knex/documentation/pull/147/commits/e3d6f48bb6f81c4bcb5aa56fd7d813d72dfb1af1

**Comment by kibertoad** [comment]
@ekeric13 Awesome work, thank you!

**Comment by heisian** [comment]
🎊

**Pull request merged**
