### PR TITLE
Add clearHaving function.

### PR DESCRIPTION
**Pull request by dmamills**
Based on #3128.

This PR adds a `clearHaving` function to the query builder, as well as a matching test case.
Also clarifies some existing comments.

### CODE REVIEW

**Comment by kibertoad** [comment]
@dmamills Could you please add documentation (https://github.com/knex/documentation) and TS typings for this change?

**Comment by dmamills** [comment]
@kibertoad no problem! see [here](https://github.com/knex/documentation/pull/190) for the matching documentation pr. I've also pushed another commit for the typescript definition.

Let me know if I missed anything!

**Comment by kibertoad** [comment]
@dmamills OK, I'm ready to merge this; could you please resolve conflicts? Sorry for the delay.

**Comment by dmamills** [comment]
@kibertoad all good now! You'll be able to close #3128 as well :)

**Comment by kibertoad** [comment]
Thanks!

**Pull request merged**
