### PR TITLE
Address concerns around count typings

### PR DESCRIPTION
**Pull request by lorefnon**
Fixes: https://github.com/tgriesser/knex/issues/3247

### CODE REVIEW

**Comment by jpike88** [comment]
https://github.com/tgriesser/knex/issues/3260
https://github.com/tgriesser/knex/issues/3259

^ these might be fixed too by this

**Comment by kibertoad** [comment]
@lorefnon Could you also backport this to `0.17` branch? This fix would definitely warrant one more release in that branch.

**Comment by lorefnon** [comment]
> should we disable linting rule for "interface-over-type-literal"?

Yeah, done. 

> @lorefnon Could you also backport this to 0.17 branch? This fix would definitely warrant one more release in that branch.

Yes, I tried cherry picking the commits on that branch and there weren't any conflicts. Do you want me to create another PR against that branch ?

**Comment by kibertoad** [comment]
Yup, would be perfect.

**Comment by kibertoad** [comment]
@lorefnon Should this be WIP or can it be merged already? Also maybe it makes sense to add TypeScript section to knex documentation to explain the registry functionality? Probably most people won't check sources for it.

**Comment by lorefnon** [comment]
I think this can be merged. I'll add a pr for ts specific docs in the documentation repo by end of the week.

**Pull request merged**
