### PR TITLE
Add inherits to postgres. Updated dialect-specific methods.

### PR DESCRIPTION
**Pull request by joeframbach**
Allow postgres tables to inherit. http://www.postgresql.org/docs/9.1/static/ddl-inherit.html

### CODE REVIEW

**Comment by bleupen** [comment]
+1

**Comment by mrbucket** [comment]
Any chance this is going to be added? I'd be happy to make any changes that are needed to get issues resolved, if no one else can/wants to.

**Comment by joeframbach** [comment]
@mrbucket I've updated to resolve conflicts.

**Comment by mrbucket** [comment]
@joeframbach Thank you for updating.
@bendrucker Is there any chance this can be merged into master? I think Joe or I would be happy to make any changes necessary to make this happen. Thank you!

**Comment by rhys-vdw** [comment]
@mrbucket @joeframbach Hadn't seen this one before. I'll merge this if we can remove the `/lib` folder that is no longer under version control. Sorry for the back and forth!

**Comment by elhigu** [comment]
I started going through old pull requests and get them merged if possible or close otherwise if they are not going to be finished.

@joeframbach Nice feature! If you rebase this one more time to top of master, I'll make sure this gets merged.

**Comment by elhigu** [comment]
@mrbucket If you still like to finish this, rebasing this to top of master and removing code from `/lib` should be enough to get this merged. Code did look good.

I'll leave this open for one more month and if still pending, close the PR and move this to issues to wait for finishing.

**Comment by joeframbach** [comment]
I've updated but Travis seems confused. Gonna close and re-open to kick off Travis.

**Comment by elhigu** [comment]
@joeframbach Awesome, thanks!

**Pull request merged**
