### PR TITLE
fix: escapeObject parameter order for Postgres dialect.

### PR DESCRIPTION
**Pull request by santegoeds**
Found this bug when I added support for writing `moment` instances (which in turn I did to fix timezone issues I had when writing `DATE` types).

```javascript
const moment = require('moment')

moment.fn.toPostgres = function () {
  return this.format()
}
```

### CODE REVIEW

**Comment by elhigu** [comment]
thanks, this needs a test case too.

**Comment by santegoeds** [comment]
Can you suggest a suitable location where I can add a test case?

**Comment by santegoeds** [comment]
I found a location for a test @elhigu.  Please let me know if you'd like me to squash the commits.

**Comment by elhigu** [comment]
Thanks! Fix looks ok, it hides worst bugs from that part of the code. 

I'm pretty sure that actually timezone + seen parameters should be completely removed and replaced with ctx object and then some more changed should be probably done to support seen and timezone parameters as they were intented...

I'm merging this one for now and add an issue about that function...

**Comment by hulbert** [comment]
@elhigu is this `toPostgres` functionality documented anywhere?

**Comment by elhigu** [comment]
@hulbert no and it should not be. It is not part of public API.

**Pull request merged**
