### PR TITLE
Add having() and on() missing methods

### PR DESCRIPTION
**Pull request by atiertant**
add missing methods:
* havingNull
* havingExists
* havingIn
* havingBetween
* onNull
* onExists
* onIn
* onBetween

### CODE REVIEW

**Comment by elhigu** [comment]
Looks good to me, I couldn't find anything to comment :)

**Comment by elhigu** [comment]
Was there another pull request for the documentation ?

**Comment by elhigu** [comment]
Looks like there is 
https://github.com/knex/documentation/pull/2

**Comment by atiertant** [comment]
exactly

Le 19 sept. 2016 18:24, "Mikael Lepistö" <notifications@github.com> a
écrit :

**Pull request merged**
