### PR TITLE
Add "udt_name" attribute to the columnInfo() method

### PR DESCRIPTION
**Pull request by sanches89**
This is useful when the field is set to array.

### CODE REVIEW

**Comment by rhys-vdw** [comment]
Looks reasonable. Any idea why this (and [all the others](http://www.postgresql.org/docs/9.4/static/infoschema-columns.html)) were omitted?

**Comment by sanchesic89** [comment]
Maybe for consistency between databases, but in my tests the other informations, apparently, is not so relevant. 
I don't know if is interesting add a parameter in the method to show all column informations.

**Comment by rhys-vdw** [comment]
So long as a minimum set of values is shared between all implementations then consistency shouldn't be an issue. However, if my understanding of the docs is correct, might it be more appropriate to do this?

```js
columns[val.column_name] = {
  type: val.data_type === 'USER-DEFINED' ? val.udt_name : val.data_type;
  maxLength: val.character_maximum_length,
  nullable: (val.is_nullable === 'YES'),
  defaultValue: val.column_default
}
```

**Comment by sanchesic89** [comment]
I agree with you and I forgot about [User Types](http://www.postgresql.org/docs/9.4/static/xtypes.html). However you suggestion won't solve the array problem.
I make same changes in my repository and  now I believe that is right.

**Comment by elhigu** [comment]
Closing due to inactivity.

**Pull request closed without merging**
