### PR TITLE
Redshift module

### PR DESCRIPTION
**Pull request by krainboltgreene**
Currently missing tests, still need to remove some things

### CODE REVIEW

**Comment by rhys-vdw** [comment]
Hi @krainboltgreene, sounds good. I'm not familiar with the overlap between redshift and postgres, but there's a lot of code duplication between the two. Would it make sense for the redshift client to inherit from postgres?

Ping me when tests are done.

**Comment by natew** [comment]
@krainboltgreene just wondering if you're active on this still? We are looking at this for an app we're building, I'm running this in a fork successfully and will attempt to help with refactoring for code duplication and tests as I go. Would be interested in sponsoring you on Patreon if you are willing.

**Comment by krainboltgreene** [comment]
@natew Hey Nate! I remember you from obtvse! :)

I haven't done anything on the fork I published to npm (`knex-redshift`) and frankly I don't want to do anymore. I appreciate the offer, but considering how painful redshift can be when doing inserts it was significantly wiser for me to shift to dumping JSON to S3 and using `COPY` (it was also WAY faster for redshift). In short: I no longer use this adapter :(

I don't believe doing inserts or updates to redshift via SQL is a good approach. The only value I see is with schema manipulation and you can actually get by using `postgres` (as long as you don't use the fancy types or main processor functions like `CURRENT_TIME`).

I'm definitely willing to help if you have any questions or if someone wants to take over, but I don't want to spend my time on this adapter.

(ps. <3 for offering, that's very awesome of you)

**Comment by krainboltgreene** [comment]
Oh, just to be clear, I ran into zero problems using the query part of knex against redshift using postgres adapter.

**Comment by natew** [comment]
@krainboltgreene Thanks for getting back in depth on that! Actually our use case is really mostly selecting, so if it already works for that things are pretty good.

I'm actually running into issues with schemas + pagination (count distinct aggregate doesn't use schema), which seems orthogonally related. Thanks for sticking around though I likely have a few questions going forward. Will update this ticket with any progress.

**Comment by doron2402** [comment]
Hi @krainboltgreene ,

Did you use knex for migration tables on RedShift?
Thanks for the PR and `knex-redshift`

**Comment by krainboltgreene** [comment]
@doron2402 No, and I'm not sure I can suggest it D:

**Comment by doron2402** [comment]
Thanks for the quick response! @krainboltgreene

**Comment by trevorsmith** [comment]
Have any decisions been made on merging this PR? We'd love to move off our forked version of knex.

Our current worker cluster isn't using this adapter for heavy writes (Kinesis is a much better choice for that) but we do use it heavily to initialize/teardown schemas, tables, and to programmatically load and unload data.

**Comment by elhigu** [comment]
Closing due to inactivity, if someone likes to finish this, please open new pull request and probably the implementation should be inherited from pg.

**Comment by krainboltgreene** [comment]
It really shouldn't.

**Comment by trevorsmith** [comment]
My pull request (https://github.com/tgriesser/knex/pull/1572) has been open for over a year and has an adapter that inherits from Postgres. I haven't received feedback from any maintainers.

I'm happy to look into updating it if there is any interest.

**Comment by doron2402** [comment]
why not just create a new module that extends Knex and adds the support for RedShift?

**Comment by trevorsmith** [comment]
@doron2402 Are you referring to my pull request?

**Comment by doron2402** [comment]
yeah, you can break it to its own node module that extends Knex

**Comment by trevorsmith** [comment]
That's what we've done privately. I can release it publicly if there is demand and the maintainers decide the don't want it as part of the core, though it's been implied for quite some time that they're open to it. I don't care either way.

**Comment by doron2402** [comment]
please do, I end up not using RedShift but I'm sure other developers will use it.

Let me know if you need help maintaining that

**Pull request closed without merging**
