### PR TITLE
Replace scripts/build.sh with build.js.

### PR DESCRIPTION
**Pull request by wolfgang42**
This makes the build script cross-platform, closing #1361.

I also added the new `build.js` to the list of files to be linted.

### CODE REVIEW

**Comment by wolfgang42** [comment]
Fixing to work on node < 4...

**Comment by wolfgang42** [comment]
For some reason node=1.10 gets into an (infinite?) loop when `npm run babel` is run from inside `build.js`. I've reproduced the issue but am having trouble diagnosing it.

**Comment by elhigu** [comment]
@wolfgang42 Ah... yep thats probably shelljs which works a bit different on node 0.10. I had problem with it outputting some really verbose messages. I'm not sure if it is the best choice after all if we need to support node 0.10... I had to make it silent with separate flag:

```js
    shelljs.exec('mkdir -p ' + tempPath, {silent: true});
    shelljs.exec('rm -f ' + path.join(tempPath, '*.deleteme'), {silent: true});
    shelljs.exec('rm -f ' + path.join(tempPath, '*.timestamp'), {silent: true});
    shelljs.exec('rm -f ' + path.join(tempPath, '*.m4'), {silent: true});
    shelljs.exec('rm -f ' + path.join(tempPath, '*.conf'), {silent: true});
```

But I'm not sure how those direct rm calls will work on windows :| Maybe you could try to set global silent flag on:

```js
var shell = require('shelljs');
shell.config.silent = true;
```

**Comment by vellotis** [comment]
This issue doesn't reproduce on windows with either v0.10.45 32bit or 64bit.

**Comment by vellotis** [comment]
I think this may be realted shelljs/shelljs#51

**Comment by wolfgang42** [comment]
@elhigu Yep, shelljs/shelljs#427:
> Every command I send to the shell via the shelljs is executed multiple times (random number, usually around 5-10).
> ...
> Unfortunately, we recently dropped support for v0.10 for future development. Since we're getting ready to release v0.7, we probably won't be able to focus on this issue. If you can figure out a fix, please feel free to submit a PR.

The `execSync` library works on 0.10, but breaks in node 5...

**Comment by wolfgang42** [comment]
@vellotis I can reproduce it on Ubuntu with 0.10.45; I haven't tried it with 0.10+Windows.

**Comment by vellotis** [comment]
@wolfgang42 Can you try to implement it as async as mentioned in shelljs/shelljs#51 ?

**Comment by wolfgang42** [comment]
This seems to have been long since obsoleted by #1616 (removed `build.sh`) and #1708 (added `build.js`).

**Pull request closed without merging**
