### PR TITLE
Support passing connection override to a query

### PR DESCRIPTION
**Pull request by kibertoad**
implements #2804

### CODE REVIEW

**Comment by kibertoad** [comment]
@elhigu If this looks OK, I'll also prepare a documentation PR.

**Comment by kibertoad** [comment]
@elhigu Any chance reviewing this could be prioritized? We were suddenly hit with a weird behavior of Google Cloud SQL and this is the only way to work around it, and using private forks is typically a terrible idea.

**Comment by kibertoad** [comment]
Documentation added, tests pass after latest fix to the master. Are there any gotchas to handling connections inside Knex that I am not aware of and that are relevant to this change?

**Comment by elhigu** [comment]
I forgot to merge this for next release... I'll do another one 😅

**Comment by kibertoad** [comment]
woohoo! thanks a lot!

**Comment by elhigu** [comment]
done!

**Comment by kibertoad** [comment]
Great news, thank you so much!

**Comment by elhigu** [comment]
Maybe after oracledb is fixed again we could think about real release... gotta go through which pull requests are still in progress.

**Comment by kibertoad** [comment]
Sounds good! I guess https://github.com/tgriesser/knex/pull/2608 is one of the most important not-yet-merged PRs, but looks like it was abandoned and no tests are coming :(. Fixing the regression for PostgreSQL streaming error handling (https://github.com/tgriesser/knex/pull/2638) would also be nice, I guess. @fcmatteo any chance you could have some time to take a look at it?

**Pull request merged**
