### PR TITLE
Merge 0.17 into master

### PR DESCRIPTION
**Pull request by kibertoad**

### CODE REVIEW

**Comment by kibertoad** [comment]
@lorefnon After this is merged, it might make sense to start first merging changes that are relevant to 0.17 into 0.17 branch, and then to merge with master via direct `0.17 -> master` pull requests. Still gonna cause conflicts in some cases (e. g. when touching typings that had their type converted from Bluebird to Promise), but hopefully will simplify usual cases.

**Comment by dgadelha** [comment]
Can we expect the `ts` extension fix to be included in this release or just the next one?

**Comment by kibertoad** [comment]
@dgadelha How urgently do you need it? I can cut a 0.17 release with it now, or including the migration extension fix in a couple of days.

**Comment by dgadelha** [comment]
Not so urgent, no problem if it takes a few days.

**Pull request merged**
