### PR TITLE
Support type-safe aliasing through refs

### PR DESCRIPTION
**Pull request by lorefnon**

### CODE REVIEW

**Comment by kibertoad** [comment]
Looks great! Restarted failed job, I'm pretty sure that's just a flaky test.

**Comment by elhigu** [comment]
@kibertoad do you remember which test failed? I couldn't locate that build from travis.

**Comment by kibertoad** [comment]
@elhigu One of the Oracle ones, but don't remember specific one. Will definitely write it down next time.

**Comment by jpike88** [comment]
this is causing type errors everywhere... is there an eta on next release?

**Comment by lorefnon** [comment]
Can you please share some examples of errors that you are receiving ? Are these with last stable release or with `@next` ?

**Comment by kibertoad** [comment]
@jpike88 Could you please try if knex@0.17.0-next6 is working correctly for you in this regard? If no, we'd like to fix it before releasing final 0.17.0.

**Comment by jpike88** [comment]
knex@0.17.0-next6 has fixed it, thanks

**Pull request merged**
