### PR TITLE
Feature/add up for migrations

### PR DESCRIPTION
**Pull request by leeallen337**
This pull request attempts to add a new feature requested in https://github.com/tgriesser/knex/issues/666 and briefly in https://github.com/tgriesser/knex/issues/352

The feature is adding a `migrate:up` functionality which would only migrate the next migration that has not been run yet to the Migrator API and the CLI

Documentation PR: https://github.com/knex/documentation/pull/194

Some other features that have been requested are a `migrate:down` and also being able to migrate up and migrate down to a specific version noted https://github.com/tgriesser/knex/issues/1550, https://github.com/tgriesser/knex/issues/352. I've started on these but don't want to put too much into one pull request

### CODE REVIEW

**Comment by elhigu** [comment]
tests seem to be failing because node 12 doesn't run oracledb tests and it still checks coverage... I'll fix travis to run coverage only on oldest node version

**Comment by kibertoad** [comment]
@elhigu Oldest version is node 6 and that skips some tests. I would suggest latest LTS instead.

**Comment by elhigu** [comment]
I meant node oldes LTS so node 8, we cant know if latest will have always all drivers ready.

**Comment by elhigu** [comment]
https://github.com/tgriesser/knex/pull/3207

**Comment by kibertoad** [comment]
Thanks!

**Pull request merged**
