### PR TITLE
Postgres question mark escaping support

### LINKED ISSUE #519: Conflict with Postgresql jsonb operators
Hi!

I have sql:

```sql
SELECT id, name, price, files->'photos'->0->>'name' as photo, annotation
FROM product
WHERE tags ?& array['17']
ORDER BY (tags->>'17')::int
LIMIT 10

```

## If i run this sql through node-postgres it work fine again:

```javascript
var pg = require('pg');

var connPg = "postgres://user:password@localhost/mydbname";
var clientPg = new pg.Client(connPg);
var sqlProductsByTags = [
  "SELECT id, name, price, files->'photos'->0->>'name' as photo, annotation ",
  "FROM product ",
  "WHERE tags ?& array['17'] ",
  "ORDER BY (tags->>'17')::int ",
  "LIMIT 10 "
];

clientPg.connect(function(err) {
  if(err) {
    return console.error('could not connect to postgres', err);
  }
  //console.log('SQL = ' + sqlProductsByTags.join(''));

  clientPg.query(sqlProductsByTags.join(''), function(err, result) {
    if(err) {
      return console.error('error select products by tags', err);
    }

    for(var i = 0, max = result.rows.length; i < max; i++) {
      console.log('name: ' +  result.rows[i].name);
    }

    clientPg.end();
  });
});
```
## If i run raw sql by knex, it fail with error (below listed): 

```javascript
var connPg = "postgres://user:password@localhost/mydbname"; 
var pg = require('knex')({
  client: 'pg',
  connection: connPg
});
var sqlProductsByTags = [
  "SELECT id, name, price, files->'photos'->0->>'name' as photo, annotation ",
  "FROM product ",
  "WHERE tags ?& array['17'] ",
  "ORDER BY (tags->>'17')::int ",
  "LIMIT 10 "
];

pg.raw(sqlProductsByTags.join(''))
```

This Error
```sh
{ [error: syntax error (at or near "$1")]
  name: 'error',
  length: 142,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '98',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  file: 'scan.l',
  line: '1053',
  routine: 'scanner_yyerror' }
```

I think that it fail because of i used jsonb operator '?&', precise only one symbol '?'
[Reference to PostgreSQL JSONB operators](http://www.postgresql.org/docs/9.4/static/functions-json.html)

### PR DESCRIPTION
**Pull request by elhigu**
Fixes #519 and #888 by adding support for `\\?` escape sequence to postgresql raw queries, which does not have bindings given. 

Uses solution based on https://github.com/tgriesser/knex/compare/qs-escapement which converts escaped question marks to place holders before replacing `?` with `$1..$n` variables of postgresql prepared statement.

Plain ignoring position binding replacement if no bindings was given (suggested in #888) did not work well, because in the end where replacement is done, may have bindings from various where statements as shown in example below.

After final SQL is created, placeholders are converted to single question marks.

e.g.
```js
knex.from('table')
  .whereRaw("(json->'field')::jsonb \\?& array['keyOne', 'keyTwo']")
  .where('id', '>', 1)
```
Is processed in few steps:
```
1# select * from "table" where (json->'field')::jsonb \\?& array['keyOne', 'keyTwo'] and "id" > ?
2# select * from "table" where (json->'field')::jsonb $Q& array['keyOne', 'keyTwo'] and "id" > ?
3# select * from "table" where (json->'field')::jsonb $Q& array['keyOne', 'keyTwo'] and "id" > $1
4# select * from "test_table_two" where (json->'field')::jsonb ?& array['keyOne', 'keyTwo'] and "id" > $1
```

### CODE REVIEW

**Comment by soldair** [comment]
this looks like it would be a good enough fix for #888 too.

**Comment by rhys-vdw** [comment]
I hate to break it to you, @elhigu, but none of your commits target source files. They're all changes to the compiled output. If you were to compile now you'd lose everything. You'll need to somehow retarget all these changes on `/src`.

**Comment by rhys-vdw** [comment]
@elhigu. Sorry, I see now that that's all the changes from previous commits. Looking now:

I wonder if we can't do something like this [here](https://github.com/elhigu/knex/blob/postgres-question-mark-escaping-support/src/dialects/postgres/index.js#L106-L113):
```js
  positionBindings: function(sql) {
    var questionCount = 0;
    return sql.replace(/(?!\\)(\?)/g, function() {
      questionCount++;
      return '$' + questionCount;
    });
```

That's two fewer calls to `replace`, and two fewer strings created as a temporary value.

**Comment by elhigu** [comment]
@rhys-vdw I think the written solution is more clear. I don't believe that this regex is bottle neck in execution, so call count should not be relevant. Though of course I will do the change if necessary to get this merged :) Also estimating performance of regex is quite hard without testing.

**Comment by elhigu** [comment]
@rhys-vdw I got interested to see actual difference and wrote fixed version of both expressions. Looks like actually making 3 simple calls instead of one more complex one is slightly faster.

1 replace version (I had to add some fixes there to make \? -> ? conversion happen and to fix questionCount incrementing to be ignored if escaped ? was found):

```js
Mikaels-MBP:~ mikaelle$ cat test1.js ; time node test1.js 
a = function(sql) {
  var questionCount = 0;
  return sql.replace(/(\\*)(\?)/g, function (match, escapes) {
    if (escapes.length % 2) { 
      return '?'; 
    } else {
      questionCount++;
      return '$' + questionCount;
    }
  });
}

console.log(a("What we have here \\? ? have here \\? ? have here \\? ? have here \\? ? have here \\? ? have here \\? ? have here \\? ? have here \\? ?"));

for (var i=0; i < 1000000; i++) {
  a("What we have here \\? ? have here \\? ? have here \\? ? have here \\? ? have here \\? ? have here \\? ? have here \\? ? have here \\? ?");
}
What we have here ? $1 have here ? $2 have here ? $3 have here ? $4 have here ? $5 have here ? $6 have here ? $7 have here ? $8

real	0m6.511s
user	0m6.484s
sys	0m0.070s
````

3 replaces version:
```js
Mikaels-MBP:~ mikaelle$ cat test2.js ; time node test2.js 
a = function(sql) {
    var questionCount = 0;
    return sql.replace(/\\\?/g, function() {
      return '$Q';
    }).replace(/\?/g, function() {
      questionCount++;
      return '$' + questionCount;
    }).replace(/\$Q/g, function() {
      return '?';
    });
}

console.log(a("What we have here \\? ? have here \\? ? have here \\? ? have here \\? ? have here \\? ? have here \\? ? have here \\? ? have here \\? ?"));
for (var i=0; i < 1000000; i++) {
  a("What we have here \\? ? have here \\? ? have here \\? ? have here \\? ? have here \\? ? have here \\? ? have here \\? ? have here \\? ?");
}
What we have here ? $1 have here ? $2 have here ? $3 have here ? $4 have here ? $5 have here ? $6 have here ? $7 have here ? $8

real	0m5.168s
user	0m5.142s
sys	0m0.058s
Mikaels-MBP:~ mikaelle$ 
```

**Comment by elhigu** [comment]
@rhys-vdw I gave this one more thought... Actually one regex has an advantage over the three separate ones. Now if user has `$Q` string in his query, it will be replaced by `?` even that it was not originally `\?`, so the solution without temporary `$Q` is more compatible.

**Comment by elhigu** [comment]
Updated pull request with more compatible substitution suggested by @rhys-vdw

**Comment by rhys-vdw** [comment]
@elhigu. Thanks for profiling that. I had incorrectly assumed that building three whole query strings would be more expensive. Good example of why profiling is always necessary when discussing performance.

I hadn't considered the other advantage, but I'm glad I provided something useful. :wink:

This all looks great.

**Pull request merged**
