### PR TITLE
Added support for `renameColumn` and double slashes

### PR DESCRIPTION
**Pull request by kirrg001**
refs #2763

### CODE REVIEW

**Comment by tgriesser** [comment]
Blah sorry this got to such a broken state ☹️ 

Been pretty bummed about the knex internals lately, currently working on rewriting them but let's get this short-term fixed for now. Also added as a collab, thought I had previously but maybe that was just for bookshelf or something.

Will make sure to test the new stuff I'm working on against the Ghost suite once it gets further along! 😄

**Comment by kirrg001** [comment]
Thanks 💃

**Comment by kibertoad** [comment]
@tgriesser What's the criteria for getting a collaborator status, btw?

**Comment by elhigu** [comment]
@kibertoad I sent you some messages about that week or two ago in gitter chat :)

**Comment by kibertoad** [comment]
@elhigu Thanks for the heads-up, I totally missed that :)

**Pull request merged**
