### PR TITLE
Add json type support for SQLite

### PR DESCRIPTION
**Pull request by kibertoad**
Implements #1036

### CODE REVIEW

**Comment by elhigu** [comment]
This one needs also integration test, which makes sure that the create query works against actual DB.

**Comment by kibertoad** [comment]
@elhigu Looks like there is one already, see `test/integration/schema/index.js`:
```
it('allows adding a field', function() {
        return knex.schema.table('test_table_two', function(t) {
          t.json('json_data', true);
        });
      });
```

It used to pass before when text was passed and it doesn't seem to have started failing now.

**Comment by bkniffler** [comment]
This is awesome, can this be released to @next? Thanks!

**Comment by kibertoad** [comment]
@bkniffler next-3 was released on Sep 27, are you sure it doesn't include it?
(we do plan to release next-4 very soon anyway, though)

**Comment by bkniffler** [comment]
Ah, I had next-2 installed since according to package.json it is the latest, at least on master.

**Pull request merged**
