### PR TITLE
Fix reference to undefined `client.initialize` method

### LINKED ISSUE #866: Error reinitializing connection pool
It was mentioned [here](https://github.com/tgriesser/knex/issues/724#issuecomment-97991976) that since `0.8.x` it should be possible to call `knex.initialize()` after `knex.destroy()` to re-initialize a connection pool.

However, I am getting the error below:

```
Object [object KnexClient] has no method 'initialize'
at Function.initialize (./node_modules/knex/lib/util/make-knex.js:44:21)
```

Using `knex@0.8.6` and `sqlite3@3.0.8`.

I have created a [Gist](https://gist.github.com/blah238/3292ef7881b3dd3c7269) demonstrating the issue.

It seems that [here](https://github.com/tgriesser/knex/blob/5e65678b32fa639843902d39603ab2050d84f10f/src/util/make-knex.js#L43) the `make-knex` utility attempts to call a non-existent `initialize` function on the client object. Is this functionality just not implemented yet, or was I misunderstanding the intention?

I could work around this by creating a new Knex instance (and remembering to replace every reference to the previous instance, which is not always straightforward given things like module caching and 3rd party code), but it would simplify things greatly by being able to reuse the same instance and just reinitializing its connection pool.

### PR DESCRIPTION
**Pull request by blah238**
Fixes #866

### CODE REVIEW

**Comment by rhys-vdw** [comment]
Hi @blah238. Great. Could you please provide a test for this to prevent regressions?

**Comment by blah238** [comment]
@rhys-vdw added a test that passes for me under SQLite3. Not sure why it's failing for mariasql.

**Comment by blah238** [comment]
@rhys-vdw does the Travis build not run the Babel build? The error would indicate that it's not rebuilding `/lib`, and I gather that PRs are not to change the contents of `/lib` either.

**Comment by rhys-vdw** [comment]
I've never investigated the CI system. If that's the case we have a problem.

**Comment by blah238** [comment]
Yeah sorry I deleted that comment, but it would appear that Travis does not have an `npm run dev` step, and you have to update `/lib` by running `npm run dev` locally and including those changes in your commit for it to be reflected in Travis.

Seems like a lot of PRs might have invalid tests because of this.

**Comment by blah238** [comment]
This is noted in [CONTRIBUTING.md](https://github.com/tgriesser/knex/blob/4304e38115bc27a6732cbdefd9f92c5bcee2094f/CONTRIBUTING.md#how-to-contribute-to-knexjs) BTW, which is why I deleted my comment.

**Comment by blah238** [comment]
Closing in favor of #1014.

**Pull request closed without merging**
