### PR TITLE
Support for joins in update statements

### LINKED ISSUE #2796: Update operations do not support joins
# Environment

Knex version: 0.15.2

# Bug

```
  await knex('table)
    .innerJoin('table2', function() {
      this.on(
        `table.id`,
        `table2.id`
      ).andOn(`table.field`, 'value')
    })
    .update({
      table.field2: 'newValue,
    })
```

This is going to execute without an error, but entire join part will be ignored and all entries will be silently updated. 

https://github.com/tgriesser/knex/issues/1534 suggests either using raw or subquery, but neither of these solutions is particularly elegant, and API-wise there is no reason why this shouldn't work, so I would consider this a bug.

### PR DESCRIPTION
**Pull request by kibertoad**
fixes #2796 
Work sponsored by Devbridge Group.

### CODE REVIEW

**Comment by kibertoad** [comment]
Ideally this needs integration tests to make sure that generated sql actually does what we hope it does, but

a) This doesn't break anything reasonable that worked before;
b) PostgreSQL update with joins were broken in worst possible way previously - silently not doing what is expected, so even if some cases break - I would call it an improvement;
c) Our integration tests are quite messy, difficult to setup and leak most of the state, so before introducing integration tests that rely on a new schema, I would prefer to do at least a little bit of cleanup that is going to take a while.

**Comment by elhigu** [comment]
I'm gonna check this out soon. This has been very much wanted feature during the years! 👍

**Comment by kibertoad** [comment]
@elhigu Finally got around to actually testing this and apparently it is slightly wrong.

In order to work it should be either 
```
  FROM table1 t1
  join table2
  on table2.id = t1.fk
  where t1.somecolumn = ?
```

or

```
  UPDATE table1 SET column = ? FROM table1 
  WHERE table1.id = table2.fk
  AND table1.somecolumn = ?
```


Neither of which are quite straightforward to implement within current code, but I'll try to work it out.
And yeah, we do need integration tests, I've started work on that in a separate branch.

**Comment by timendez** [comment]
@kibertoad @elhigu Is this feature dead or was it implemented in a different PR?

**Comment by kibertoad** [comment]
@timendez "Half-baked" is a better description than "dead", it's not correct for all DBs and there are no integration tests. I want to complete it when I have some time, but if you want to volunteer to finish the deed, that'd tremendously speed it up.

**Pull request closed without merging**
