### PR TITLE
Add tests for specifying explicit pg version

### PR DESCRIPTION
**Pull request by kibertoad**

### CODE REVIEW

**Comment by kibertoad** [comment]
@elhigu Tried to find something like this, but couldn't find anything that would be setting {version} option for the knex. Have I missed it somewhere?

**Comment by elhigu** [comment]
I went to look the code, that implements version support, checked commit where it was written with "Blame" and found this: https://github.com/tgriesser/knex/pull/1993/files

**Comment by elhigu** [comment]
Git archeology :D

**Comment by kibertoad** [comment]
Ahahahaha, yeah.
Aha, so there are tests, but they cover different ground (branching in internal logic based on version) and not version resolution logic per se, so there doesn't seem to be direct overlap, hence makes sense to keep new tests.

**Pull request merged**
