### PR TITLE
Correct connection URL parsing for MSSQL

### PR DESCRIPTION
**Pull request by h0vhannes**
Use connection.server instead of connection.host when connecting to MSSQL

### CODE REVIEW

**Comment by rhys-vdw** [comment]
Thanks. Would you be able to add test coverage for this?

**Comment by h0vhannes** [comment]
Sure, just don't know where to add tests for this. Is it integration or, maybe, tape ?

**Comment by rhys-vdw** [comment]
Thanks. If there are none already then I tape is preferable for new tests.

**Comment by h0vhannes** [comment]
Ok, there are tests for connection URL parser in tape, so I'll add tests there.

**Comment by wubzz** [comment]
Good catch on this. Just to verify, was this done because it wasn't working properly in 0.10? Given #1239 the initiation should have worked regardless of this. But I do agree this was needed as well.

**Comment by h0vhannes** [comment]
Yes, 0.10 doesn't work with MSSQL connection urls

**Pull request merged**
