### PR TITLE
Update package.json to use latest node-postgres

### LINKED ISSUE #1371: Postgres authentication failing on node version 6.0
After upgrading node version 6.0, authentication to my Postgres database fails when instantiating the knex client. Downgrading to 5.11 made it work. 

Here is the error message I was getting.

`Knex:Error Pool2 - error: password authentication failed for user "$user"`

### PR DESCRIPTION
**Pull request by mdrmuhaimin**
Resolve #1371
- Fix pg authentication error 
- Update package.json to use pg 4.5.5

### CODE REVIEW

**Comment by wubzz** [comment]
No tests failing so I'm going to assume this is fine, and merging for the sake of 6.0.

**Comment by jordansexton** [comment]
Would it be reasonable to publish a release for this on npm?

**Comment by wubzz** [comment]
I believe 0.11 is supposed to be getting published, right @rhys-vdw ?

**Comment by andrew-w-ross** [comment]
Could this version be published please.

**Comment by oliverhr** [comment]
Still receiving the same error with node 6.0.0 and 6.1.0

```Knex:Error Pool2 - error: password authentication failed for user ...```

knex version:  0.11.1
postgresql version: 9.4

```
└─┬ knex@0.11.1
  ├── bluebird@3.3.5
  ├─┬ chalk@1.1.3
  │ ├── ansi-styles@2.2.1
  │ ├── escape-string-regexp@1.0.5
  │ ├─┬ has-ansi@2.0.0
  │ │ └── ansi-regex@2.0.0
  │ ├── strip-ansi@3.0.1
  │ └── supports-color@2.0.0
  ├─┬ commander@2.9.0
  │ └── graceful-readlink@1.0.1
  ├─┬ debug@2.2.0
  │ └── ms@0.7.1
  ├── inherits@2.0.1
  ├── interpret@0.6.6
  ├─┬ liftoff@2.2.1
  │ ├── extend@2.0.1
  │ ├─┬ findup-sync@0.3.0
5.0.15
  │ │   ├─┬ inflight@1.0.4
  │ │   │ └── wrappy@1.0.1
  │ │   ├─┬ minimatch@3.0.0
  │ │   │ └─┬ brace-expansion@1.1.4
  │ │   │   ├── balanced-match@0.4.1
  │ │   │   └── concat-map@0.0.1
  │ │   ├── once@1.3.3
  │ │   └── path-is-absolute@1.0.0
  │ ├── flagged-respawn@0.3.2
  │ ├── rechoir@0.6.2
  │ └── resolve@1.1.7
  ├── lodash@4.12.0
  ├── minimist@1.1.3
  ├─┬ mkdirp@0.5.1
  │ └── minimist@0.0.8
  ├── pg-connection-string@0.1.3
  ├─┬ pool2@1.3.4
  │ ├── debug@2.2.0
  │ ├── double-ended-queue@2.1.0-0
  │ ├── hashmap@2.0.5
  │ └── simple-backoff@1.0.0
  ├─┬ readable-stream@1.1.14
  │ ├── core-util-is@1.0.2
  │ ├── isarray@0.0.1
  │ └── string_decoder@0.10.31
  ├─┬ tildify@1.0.0
  │ └── user-home@1.1.1
  └── v8flags@2.0.11
```

**Comment by wubzz** [comment]
@oliverhr In knex `pg` is just a devDependency, meaning you have to `npm install pg` on your own. Make sure you update your seperate pg package manually.

Unless you are referring to a local dev-environment of knex you're trying to work on in which case this could be wrong.

**Comment by oliverhr** [comment]
it works, thank you I have installed and old one

**Comment by rhys-vdw** [comment]
@jordansexton @andrew-w-ross It's been published now btw.

**Comment by jordansexton** [comment]
Yup, already using it :) Thanks!

**Comment by andrew-w-ross** [comment]
@rhys-vdw Thanks so much

**Pull request merged**
