### PR TITLE
chore: Update dependencies. Remove estraverse

### PR DESCRIPTION
**Pull request by kibertoad**
Removes estraverse as it was only needed to run tests in Node 4, which is no longer supported. Also bump dependency versions.

### CODE REVIEW

**Comment by kibertoad** [comment]
@elhigu Any ideas why mssql might be consistently failing on Node 6?

**Comment by elhigu** [comment]
Looks like the problem is that mssql server doesn't have enough time to startup. Maybe I'll need to setup longer timeout there. I've seen this happening on some other PRs as well.

**Comment by kibertoad** [comment]
@elhigu Done!

**Comment by kibertoad** [comment]
@elhigu Judging by https://travis-ci.org/tgriesser/knex/jobs/401093618 it looks like it's not just about not having enough time to startup, but about not starting at all :(

**Comment by elhigu** [comment]
@kibertoad looks like it or could be that or it just takes sometimes huge amount of time... sometimes CI systems work really slow. It never seems to fail when I just retrigger single build env :( I need to figure why that happens (maybe print mssql logs after timeout or something like that helps)

**Comment by elhigu** [comment]
Looks like the real problem is that creating testdatabase fails some times https://travis-ci.org/tgriesser/knex/jobs/401116305#L1074 should be pretty easy to fix...

**Comment by elhigu** [comment]
Yeah mssql init now works in a robust manner: https://travis-ci.org/tgriesser/knex/jobs/401325827 in line  977 things would have failed earlier and knex_test database would never have been created.

**Pull request merged**
