### PR TITLE
Fix issue tgriesser/knex#1180

### PR DESCRIPTION
**Pull request by maxcnunes**
Fix the problem on installing project from the github.

### CODE REVIEW

**Comment by maxcnunes** [comment]
Actually it still not working. Because it allow install the project without that error of `cli.js` not found. But since the build is only applied during the pre-publish. The `lib` files are not available on installing from github.
I don't like the idea of building the lib during the postinstall. Because it  requires installing "useless" dependencies for production environment such as babel. And it makes the installing slower.
There is a proposal for NPM [include a prepublish for Git](https://github.com/npm/npm/issues/3055). But I guess it will not be implemented.
Seems most projects doesn't provide the build files on installing from git. So I guess the best option for #1180 is just not provide the lib on git. And anyone installing from git, changes their own fork-branch to include the lib files.

**Comment by elhigu** [comment]
I think that this change would still be good. This way one can install from github and then add post install scripts to own project which builds the knex if he really wants to use something from github. To me this fix would be enoguh to close #1880.

**Comment by elhigu** [comment]
This would also need manual testing since nothing in test suite is actually running the `cli.js` client installed by npm scripts.

**Comment by maxcnunes** [comment]
Nowadays installing from github does not include the scripts folder. Which has the `build.sh`. I guess because is not included into the [files](https://github.com/tgriesser/knex/blob/master/package.json#L95) property. So to allow users installing from github and later building the project I think would be good include the scripts folder as well.
We could use `.npmignore` to ignore it and even the `src` folder on installing from npm. I guess the `.npmignore` is only applied on publishing to npm. So would not affect those installing from github.
@elhigu  I can test these ideas and apply them if you think they are a good approach for the problem.

**Comment by elhigu** [comment]
@maxcnunes Sounds good. I don't know much about npm packaging / so I cannot anticipate if that really is viable, but would be great if you can test it :+1:

**Comment by vellotis** [comment]
https://docs.npmjs.com/files/package.json#files

> ### files 
>
> The "files" field is an array of files to include in your project. If you name a folder in the array, then it will also include the files inside that folder. (Unless they would be ignored by another rule.)
> 
> You can also provide a ".npmignore" file in the root of your package or in subdirectories, which will keep files from being included, even if they would be picked up by the files array. The **.npmignore** file works just like a **.gitignore**.

So package.json specification confirms @maxcnunes words.

I was thinking if there could be a way to build (+ babel installing) with `postinstall` if `lib` directory is missing. This way it is not needed to explicitly invoke building from depending project.

#1425 would be a great improvement along with this one.

**Comment by maxcnunes** [comment]
Yeah. The solution I was thinking was exactly this one using `postinstall`. Although I don't have time to implement this right now. Please, feel free anyone to take over.

**Comment by vellotis** [comment]
I will look into it in few days.

**Comment by tgriesser** [comment]
So the latest 0.12 should allow you to install from github, but for now you'll also need to configure a script yourself that goes into the knex directory and runs `npm install` & `npm run build`

**Comment by vellotis** [comment]
@tgriesser 
There is no need for separate script that goes into the knex directory and runs ``npm install & npm run build`. It can be handled the same way as solved in https://github.com/tgriesser/bookshelf/pull/1403

**Comment by tgriesser** [comment]
Yeah, I guess I was just trying to make it possible but discouraged to install from github. But yeah, `buildDependencies` seems like a good compromise. Feel free to open a PR.

**Pull request closed without merging**
