### PR TITLE
Bugfix/query event sql string

### LINKED ISSUE #2549: v0.13.0 to v0.14.4 breaking sql string change for on query event
My project is currently on version 0.13.0, and I'm using the `query` event to print the full sql with the bindings injected into the string.

Typescript code:
```
this.knex.client.on('query', (data: {sql: string; bindings: any; }) => {
    var printSql = this.knex.raw(data.sql, data.bindings).toString();
    console.log(printSql);
});
```

This was possible because the `data.sql` string returns the string with `?` and `??` as the placeholder values, so using it in a knex raw object with the bindings would produce the complete query.

However when upgrading to 0.14.4, the `data.sql` string now returns the query string using the `$1, $2, $3...` placeholders which makes it impossible to easily log the complete query.

Examples:
On v0.13.0 it would return something like
`select * from "tableName" where "id" = ?`

Now on 0.14.4 it returns something like
`select * from "tableName" where "id" = $1`

Was this an intended change, and is there an easier way to compute and print the complete query?

### PR DESCRIPTION
**Pull request by wubzz**
Fixes #2549

### CODE REVIEW

**Comment by elhigu** [comment]
Looks good. Should this be marked as breaking change?

Now that there is test for the format I think that should be mentioned in documentation. I just looked those event docs and they seem pretty bad, not telling at all what kind of data is passed to event handler.

**Comment by wubzz** [comment]
I don't believe this is a breaking change, it should be quite the opposite since it restores previous functionality.

I created https://github.com/knex/documentation/issues/103 for docs as a seperate issue. As mentioned in #2549 it needs a complete overhaul, really.

This being the only thing merged since 0.14.5 I'll try to publish 0.14.6 later if I can.

**Comment by elhigu** [comment]
> I don't believe this is a breaking change, it should be quite the opposite since it restores previous functionality.

Yep, this is one of those less clear cases, when functionality is changed, but since it hadn't been documented earlier, its kind of 50%/50% if it should be marked as breaking or not... especially because last time it was changed by accident.

**Comment by elhigu** [comment]
I think I'll make next knex release to be 0.15 and add this to one of breaking changes and explain in log that this has been gone back and forward since 0.13.0 (this has clearly caused issue to someone, so I think reporting this change wont hurt). Maybe there will be some real breaking changes too.

**Pull request merged**
