### PR TITLE
Testing removal of 'skim'

### PR DESCRIPTION
**Pull request by wubzz**
Temporary, might be closed.

### CODE REVIEW

**Comment by wubzz** [comment]
@tgriesser This function is 4 years old and hasn't been changed. This is a long shot in the dark, but do you happen to remember the reasoning behind it? 😄 

No tests are failing after removing it. Still not sure if that's reliable enough, tho.

Currently this is a progressive performance bottleneck as described in https://github.com/tgriesser/knex/issues/2518#issuecomment-369145795

**Comment by elhigu** [comment]
Maybe it converts random classes etc. returned from drivers to plain objects?

**Comment by elhigu** [comment]
Anyways I'm pretty if it is wanted then it would be faster to do with plain javascript loop. @koskimas has done lots of micro optimizations to obejction, he probably remembers from top of the head if there is something really inefficient in that implementation.

**Comment by tgriesser** [comment]
> Maybe it converts random classes etc. returned from drivers to plain objects?

Exactly it. I forget which drivers it was now though

**Comment by wubzz** [comment]
That makes sense.

Pressumably the only reason it affects so many dialects is because copy-paste when adding new dialects. I imagine mssql can be one such case.

**Comment by elhigu** [comment]
Looks like this could be used also to copy object own properties to plain object https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

If I didn't do something badly wrong with object assign skimming is ~20x faster https://jsperf.com/knex-skim (on chrome at least)

**Comment by koskimas** [comment]
@elhigu I was about to suggest the same. V8 team has spent some time optimizing Object.assign recently. It will probably get even faster with node 10.

**Comment by koskimas** [comment]
I think you could even skip the whole thing if `obj.constructor === Object`

**Comment by wubzz** [comment]
@tgriesser @elhigu I'm comfortable removing this for both MySQL (from Tim's comment) and Postgres. I can't speak for other dialects, tho.

Anything we can do to speed up resultset is a win-win situation imo.

If you're ok with this I can update the PR.

**Comment by elhigu** [comment]
@wubzz I believe this is good to go, just need to remember write to changelog about that returned row types might not be plain js objects anymore on those dialects, which were skimmed earlier.

**Pull request merged**
