### PR TITLE
Support node-mssql 4.0.0 

### LINKED ISSUE #1999: node-mssql 4..0.0 incompatibility
With the new release of node-mssql 4.0.0 knex "dialect" is no longer compatible.

" var connection = new _this.driver.Connection(_this.connectionSettings);"

Connection has been renamed ConnetionPool. Changing this stops knex from crashing but returned me no data.

### PR DESCRIPTION
**Pull request by ncwgf**
Only support node-mssql@^4.0.0

Try to fix #1999

### CODE REVIEW

**Comment by elhigu** [comment]
It would be better to just update the node-mssql from package.json and support only node-mssql >4.

Now one of the code paths gets never tested.

**Comment by jjg1914** [comment]
Are there any plans for merging this soon, possibly for a 0.13.1 change? This is blocking me from upgrading mssql, and I'd help in any necessary (big knex.js fan!)

**Comment by elhigu** [comment]
Thanks!

**Comment by elhigu** [comment]
yes

**Pull request merged**
