### PR TITLE
Use extension from knexfile filename for generating migrations unless overriden

### LINKED ISSUE #3003: migrate:make fails with TypeScript
# Environment

Knex version: 0.16.3 (Using TypeScript knexfile)
Database + version: PostgreSQL 10.5
OS: Windows 10 Pro 64 Bit

# Bug

When running `knex migrate:make somename`, this is the output:
```
Requiring external module ts-node/register
Using environment: development
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:166:7)
    at directories.map.directory (X:\Code\node\knextest\node_modules\knex\lib\migrate\MigrationGenerator.js:82:28)
    at Array.map (<anonymous>)
    at MigrationGenerator._absoluteConfigDirs (X:\Code\node\knextest\node_modules\knex\lib\migrate\MigrationGenerator.js:81:24)
    at MigrationGenerator._ensureFolder (X:\Code\node\knextest\node_modules\knex\lib\migrate\MigrationGenerator.js:41:23)
    at MigrationGenerator.make (X:\Code\node\knextest\node_modules\knex\lib\migrate\MigrationGenerator.js:35:17)
    at Migrator.make (X:\Code\node\knextest\node_modules\knex\lib\migrate\Migrator.js:122:27)
    at Command.commander.command.description.option.action (X:\Code\node\knextest\node_modules\knex\bin\cli.js:179:10)
    at Command.listener (X:\Code\node\knextest\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (X:\Code\node\knextest\node_modules\commander\index.js:654:12)
    at Command.parse (X:\Code\node\knextest\node_modules\commander\index.js:474:21)
    at Liftoff.invoke (X:\Code\node\knextest\node_modules\knex\bin\cli.js:278:13)
    at Liftoff.execute (X:\Code\node\knextest\node_modules\liftoff\index.js:203:12)
    at module.exports (X:\Code\node\knextest\node_modules\flagged-respawn\index.js:51:3)
```

This is the content of my `knexfile.ts`:

```ts
module.exports = {
  development: {
    client: 'pg',
    connection: {
      host: 'localhost',
      database: 'postgres',
      user: 'postgres',
      password: 'pw',
    },
    migrations: {
      directory: 'migrations',
    },
  },
};
```

Some additional details:
- `knex migrate:make somename` works if I change knexfile extension to `.js`. (knex 0.16.3)
- `knex migrate:make somename` works like it should with TypeScript knexfile when using knex 0.15.1 and `@types/knex` 0.15.1 package.
- I have not tried different database engines or the versions between knex 0.15.1 - 0.16.3.

### PR DESCRIPTION
**Pull request by kibertoad**
fixes #3003

### CODE REVIEW

**Comment by dgadelha** [comment]
It works for me, is it possible to release this?

**Comment by kibertoad** [comment]
@dgadelha 0.18.0 is not yet ready, would next-1 work for you? Also master is not transpiled anymore, so you can directly depend on branches and commits.

**Comment by dgadelha** [comment]
It would, can we depend a commit directly from npm? Thought you had to publish it there.

**Comment by kibertoad** [comment]
You definitely can! https://medium.com/@jonchurch/use-github-branch-as-dependency-in-package-json-5eb609c81f1a

**Pull request merged**
