### PR TITLE
Add a queryEnd event that contains the response

### PR DESCRIPTION
**Pull request by pursual**
This allows for better logging and debugging

### CODE REVIEW

**Comment by pursual** [comment]
Anyone?

**Comment by rhys-vdw** [comment]
Hi @pursual, shouldn't the event get the response object as an argument?

Also `"queryEnd"` feels awkward. How about `"response"`?

Also please add documentation and tests.

**Comment by chrisbroome** [comment]
Should the `__knexUid` be the same in both `this.connection.__knexUid` and `runner.connection.__knexUid`? If so I'd assign it to a temporary variable so that it doesn't change out from under you. The way I see the events working is that you can correlate `query` with `queryEnd` using the `__knexUid`. If this isn't the case, ignore my comment.

**Comment by pursual** [comment]
Perhaps it should be the response object, I haven't explored that. It does work for logging as is, but I am not familiar with the source enough to say if this is the ideal method. I have used this code personally for logging, but it is kind of annoying every time I start a new project to have to insert it into Knex.

**Comment by rhys-vdw** [comment]
@pursual My point was that it should get all relevant information - query and response.

PR will not be merged until tests and documentation are supplied.

**Comment by ngoctranfire** [comment]
When will this be merged in?

**Comment by rhys-vdw** [comment]
@ngoctranfire 

> PR will not be merged until tests and documentation are supplied.

Please read thread before asking questions.

**Comment by rhys-vdw** [comment]
Actually this branch has gone completely stale, it targets the `/lib` directory which no longer exists. If anybody wishes to see this feature implemented please refer to discussion on #1203.

**Pull request closed without merging**
