### PR TITLE
Refactor migrator

### PR DESCRIPTION
**Pull request by kibertoad**
refs #2690

### CODE REVIEW

**Comment by kibertoad** [comment]
@elhigu In order to make implementation of a new feature easier (as well as make it more testable), I've refactored original code to be more modular. Could you please take a look and decide whether that is an acceptable solution?

**Comment by kibertoad** [comment]
@tgriesser Can this be reviewed before there is another set of sweeping changes, e. g. due to Typescriptization?

**Comment by tgriesser** [comment]
Yep I will try to take a look tonight or tomorrow, though there shouldn't be any changes as crazy as prettier, TS branch will just be continually merging the changes to master into it.

**Comment by kibertoad** [comment]
Thank you :)

**Comment by kibertoad** [comment]
@tgriesser Any ETA updates :)?

**Pull request merged**
