### PR TITLE
Add oracledb stream support

### PR DESCRIPTION
**Pull request by natevecc**
I took a stab at adding support for the Client_Oracledb class to use oracledb#queryStream method to stream results through knex. I added a test but not sure if more is needed so please let me know if I need to make more tests or change how I setup the streaming feature. Finally I wasn't sure how to get the tests working locally with oracledb and an oracle db so I'm hoping the tests will work correctly in travis but if not I'd appreciate some help in getting the tests working locally and I'll update the docs as well.

### CODE REVIEW

**Comment by elhigu** [comment]
Sorry for the huge delay, I hadn't noticed this one earlier, looks like a pull request that should be merged in after conflicts are fixed. Setting up oracledb locally is a bit painful. If I recall correctly I did it with vagrant + VirtualBox earlier... Would be good to have some vagrant file for setting it up locally, probably I'll do that if I need to set it up again at some point.

**Comment by vegarringdal** [comment]
So knex.js with oracledb streams is not supported atm ?

**Comment by natevecc** [comment]
Sorry I've moved on from the project where I was using this and don't know when I'll have time to get back to it. I'll try fix the conflicts soon but if someone else could handle setting up the tests that'd be much appreciated.

**Comment by elhigu** [comment]
Closing incomplete PR, can be reopened if completed.

**Pull request closed without merging**
