### PR TITLE
PR for #1297

### PR DESCRIPTION
**Pull request by gmcdowell**
A PR for mssql dialect tablecompiler.js Create Table logic incorrect #1297

### CODE REVIEW

**Comment by elhigu** [comment]
This should have also test case for the fix.

**Comment by wubzz** [comment]
@gmcdowell Any update on this one? Would be great to get it published with 0.11.

**Comment by gmcdowell** [comment]
Apologies. Family stuff going on at present. Will try next week

**Comment by wubzz** [comment]
Closing this as #1362 is merged.

**Pull request closed without merging**
