### PR TITLE
Add node 6

### PR DESCRIPTION
**Pull request by Vanuan**

### CODE REVIEW

**Comment by Vanuan** [comment]
```
  1) Integration Tests mysql | mysql Schema createTable accepts table names starting with numeric values:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.

```

**Comment by Vanuan** [comment]
Maybe it's just slowness.

**Comment by Vanuan** [comment]
So #1369 isn't covered by tests.

**Comment by rhys-vdw** [comment]
Can you add a comment explaining why the timeout is there please?

**Comment by Vanuan** [comment]
I don't really know. It looks like Node 6 is just slower for some reason.

**Comment by rhys-vdw** [comment]
Sorry, I man a comment in the code explaining why it's there (Travis, node 6). It's a bit mysterious as it is. It doesn't have to fully explain why it's broken.

**Comment by Vanuan** [comment]
Node is crashing BTW. It's strange that travis didn't fail:

```
Loading config: /home/travis/build/tgriesser/knex/test/.istanbul.yml
Knex:warning - sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).
Knex:warning - sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.
==== JS stack trace =========================================
Security context: 0x6bc00bc9fa9 <JS Object>#0#
    1: .node [module.js:568] [pc=0x21603eb9a204] (this=0x2d9ea50fb379 <an Object with map 0xb447c472731>#1#,module=0x17a028df9f29 <a Module with map 0xb447c417be1>#2#,filename=0x17a028df9f01 <String[103]: /home/travis/build/tgriesser/knex/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node>)
    2: load [module.js:456] [pc=0x21603e738e72] (this=0x17a028df9f29 <a Module with map 0xb447c417be1>#2#,filename=0x17a028df9f01 <String[103]: /home/travis/build/tgriesser/knex/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node>)
    3: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x21603e73899d] (this=0x6bc00b04189 <undefined>,module=0x17a028df9f29 <a Module with map 0xb447c417be1>#2#,filename=0x17a028df9f01 <String[103]: /home/travis/build/tgriesser/knex/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node>)
    4: _load [module.js:407] [pc=0x21603e7345e2] (this=0x2d9ea50fb3f9 <JS Function Module (SharedFunctionInfo 0x2d9ea50277f1)>#3#,request=0x17a028df3141 <String[103]: /home/travis/build/tgriesser/knex/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node>,parent=0x17a028ba3601 <a Module with map 0xb447c417be1>#4#,isMain=0x6bc00b04299 <false>)
    5: require [module.js:~463] [pc=0x21603e77a84b] (this=0x17a028ba3601 <a Module with map 0xb447c417be1>#4#,path=0x17a028df3141 <String[103]: /home/travis/build/tgriesser/knex/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node>)
    6: require(aka require) [internal/module.js:20] [pc=0x21603e7427a6] (this=0x6bc00b04189 <undefined>,path=0x17a028df3141 <String[103]: /home/travis/build/tgriesser/knex/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node>)
    7: /* anonymous */ [/home/travis/build/tgriesser/knex/node_modules/sqlite3/lib/sqlite3.js:4] [pc=0x21603ec58b9e] (this=0x17a028ba3651 <an Object with map 0x218cd2607bc9>#5#,exports=0x17a028ba3651 <an Object with map 0x218cd2607bc9>#5#,require=0x17a028ba9251 <JS Function require (SharedFunctionInfo 0x2d9ea5057c99)>#6#,module=0x17a028ba3601 <a Module with map 0xb447c417be1>#4#,__filename=0x17a028ba35d9 <String[69]: /home/travis/build/tgriesser/knex/node_modules/sqlite3/lib/sqlite3.js>,__dirname=0x17a028ba91e9 <String[58]: /home/travis/build/tgriesser/knex/node_modules/sqlite3/lib>)
    8: _compile [module.js:541] [pc=0x21603e741944] (this=0x17a028ba3601 <a Module with map 0xb447c417be1>#4#,content=0x17a028ba5eb1 <Very long string[5550]>#7#,filename=0x17a028ba35d9 <String[69]: /home/travis/build/tgriesser/knex/node_modules/sqlite3/lib/sqlite3.js>)
    9: .js [module.js:550] [pc=0x21603e73a46b] (this=0x31c2c6d1159 <an Object with map 0xb447c472789>#8#,module=0x17a028ba3601 <a Module with map 0xb447c417be1>#4#,filename=0x17a028ba35d9 <String[69]: /home/travis/build/tgriesser/knex/node_modules/sqlite3/lib/sqlite3.js>)
   10: .js [/home/travis/build/tgriesser/knex/node_modules/istanbul/lib/hook.js:109] [pc=0x21603e8b32c7] (this=0x2d9ea50fb379 <an Object with map 0xb447c472731>#1#,module=0x17a028ba3601 <a Module with map 0xb447c417be1>#4#,filename=0x17a028ba35d9 <String[69]: /home/travis/build/tgriesser/knex/node_modules/sqlite3/lib/sqlite3.js>)
   11: load [module.js:456] [pc=0x21603e738e72] (this=0x17a028ba3601 <a Module with map 0xb447c417be1>#4#,filename=0x17a028ba35d9 <String[69]: /home/travis/build/tgriesser/knex/node_modules/sqlite3/lib/sqlite3.js>)
   12: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x21603e73899d] (this=0x6bc00b04189 <undefined>,module=0x17a028ba3601 <a Module with map 0xb447c417be1>#4#,filename=0x17a028ba35d9 <String[69]: /home/travis/build/tgriesser/knex/node_modules/sqlite3/lib/sqlite3.js>)
   13: _load [module.js:~381] [pc=0x21603eb178a3] (this=0x2d9ea50fb3f9 <JS Function Module (SharedFunctionInfo 0x2d9ea50277f1)>#3#,request=0x324b2eb2ff99 <String[7]: sqlite3>,parent=0x2891203eb5f1 <a Module with map 0xb447c417be1>#9#,isMain=0x6bc00b04299 <false>)
   14: require [module.js:~463] [pc=0x21603e77a84b] (this=0x2891203eb5f1 <a Module with map 0xb447c417be1>#9#,path=0x324b2eb2ff99 <String[7]: sqlite3>)
   15: require(aka require) [internal/module.js:20] [pc=0x21603e7427a6] (this=0x6bc00b04189 <undefined>,path=0x324b2eb2ff99 <String[7]: sqlite3>)

```

**Comment by Vanuan** [comment]
Ah, it's a warning 0_o

**Comment by Vanuan** [comment]
Probably it was a temporary glitch.

**Comment by rhys-vdw** [comment]
Also I'm getting warnings on install from `graceful-fs`, apparently the version needs to be bumped to version 4 to be compatible with Node 6.

**Comment by rhys-vdw** [comment]
Well, I'll merge this one. `graceful-fs` is a different issue. Thanks! 👍

**Pull request merged**
