### PR TITLE
add travisCi to oracle feature

### PR DESCRIPTION
**Pull request by williamgueiros**
see more information on #1491 and #990

### CODE REVIEW

**Comment by williamgueiros** [comment]
@elhigu  please add environment variables

if you prefere add all, using don't display information on console.

**Comment by elhigu** [comment]
@tgriesser @rhys-vdw Looks like I don't have enough rights to set those variables. Could you add them?

**Comment by vschoettke** [comment]
I think pull requests will not be tested if the TravisCI script requires environment variables (because somebody might just add an echo of that variable). The best way would be for Oracle to supply a public url for downloading Oracle XE or any other mean (e.g. Docker image)

**Comment by williamgueiros** [comment]
@vschoettke i 💚  the ideia.
but angry to the oracle license 👎 , i don't remember there i read that, we do not have permission to copy and distribution oracle XE

**Comment by rhys-vdw** [comment]
Hey guys, it seems I am able to modify environment variables, but could somebody guide me through the process? Do I need to create an Oracle account for knex?

**Comment by rhys-vdw** [comment]
> I think pull requests will not be tested if the TravisCI script requires environment variables

Yes, you're correct - thanks for the heads up. Not ideal.

On the bright side a local branch [succeeds](https://travis-ci.org/tgriesser/knex/builds/138286598)!

**Comment by williamgueiros** [comment]
@rhys-vdw  I ❤️ the idea @vschoettke 

but the problem to me, is the oracle license.

@vschoettke do you start this feature ??

**Comment by rhys-vdw** [comment]
Okay, so I want to get this merged even if we don't support Oracle or PR's. A solution like @vschoettke's suggestion would be ideal, but that shouldn't prevent us from running oracle tests on branches of this repository.

In the short term I think we must skip Oracle integration testing in PR's. This means we's need to merge into a local branch to see if PR's pass Oracle integration tests in CI. Still an improvement over the current state of things.

If I understand correctly, this new environment variable `DIALECT` means we end up running all our integration tests twice. We already support listing dialects using the [`DB` environment variable](https://github.com/tgriesser/knex/blob/b21156d92085a859efc2d77f8cc606bf41d781cf/test/knexfile.js#L9). Since this PR hasn't modified `DB` or its default value we are not actually running the tests (including in my the successful branch I linked to [above](https://github.com/tgriesser/knex/pull/1503#issuecomment-226701058)).

It is possible to check whether the [current branch is a pull request](https://docs.travis-ci.com/user/pull-requests#Security-Restrictions-when-testing-Pull-Requests). Perhaps we can use this to conditionally skip some tests?

The logic could be something like this:

1. If we are *not* testing a pull request, include `oracle` in the DB environment variable along with the other dialects.
2. If `oracle` is included in `DB` then install download an install Oracle as per this PR's implementation.

This way we'll have a single build per node version, conditionally testing Oracle if available.

Thoughts?

**Comment by elhigu** [comment]
@williamgueiros Actually oracle license seems really permissive http://www.oracle.com/technetwork/licenses/database-11g-express-license-459621.html It allows package DB with your own application and it allow to redistribute it too if you require your users to agree with the original license.

**Comment by tgriesser** [comment]
This would be awesome to get in here - @williamgueiros @vschoettke what can I do to get this moving forward. Also while I'm here, for those who know oracle well, can anyone tell me what's supposed to be [going on here](https://github.com/tgriesser/knex/blob/53d089bffbde6e16aa79652d258154a67dec8c0a/src/dialects/oracledb/query/compiler.js#L70-L79). 

That `usingClause` value is never actually used anywhere, the newest eslint caught that.

**Pull request closed without merging**
