### PR TITLE
Execute tests on Node.js 11

### PR DESCRIPTION
**Pull request by kibertoad**

### CODE REVIEW

**Comment by kibertoad** [comment]
Fails on sqlite dependency, issue raised: https://github.com/mapbox/node-sqlite3/issues/1063

**Comment by elhigu** [comment]
Some test failures suggests that hardcoded mssql driver version is not working 🤔

**Comment by kibertoad** [comment]
@elhigu Huh? What do you mean?

**Comment by elhigu** [comment]
I'm not sure, but just saw these lines during test run:
https://travis-ci.org/tgriesser/knex/jobs/445284075#L3048

**Comment by kibertoad** [comment]
@elhigu TBH, I'm more surprised that other node versions didn't fail, somehow "^4.1.0" got into our package.json which obviously resolves to latest 4.x.

**Pull request merged**
