### PR TITLE
Version upgrade guide

### PR DESCRIPTION
**Pull request by kibertoad**
I've tried to include cases that are plausible to be found in real production environments. If someone have their favourite breaking change not mentioned, please let me know.

### CODE REVIEW

**Comment by elhigu** [comment]
Very nice :+1:

**Comment by kibertoad** [comment]
Merged as-is, we can improve going forward.

**Comment by willmorgan** [comment]
@kibertoad Looks good!

**Comment by kibertoad** [comment]
@willmorgan Thanks for checking it out!

**Pull request merged**
