### PR TITLE
Provide Pool2 a ping method to test a connection

### PR DESCRIPTION
**Pull request by vellotis**
#892

This is how it should be done for Pool2. Every client dialect must implement its ping method for the used driver. At the moment only mysql/2, maria and pg native drivers are capable of doing this kind of check. 

If ping method fails then connection will be destroyed from the pool. Otherwise (like at the moment) Pool2 resource pool thinks, that the connection is still valid. So it tries to use it for the queued requests over and over again without releasing it and acquiring a new one.

Sadly I don't have time to set up all the databases to run the tests. I would be glad if somebody could run them and confirm the merge.

### CODE REVIEW

**Comment by zachary822** [comment]
I would like to, as a user, add to this that it works nicely for mysql2.
I changed the database wait_timeout and interactive_timeout to 1 second.
The original knex would throw an error saying "This socket has been ended by the other party".
It does not happen with this commit.

**Comment by indeyets** [comment]
@rhys-vdw can you check this one please? (sorry if I'm wrong to ping you, but it looks like you're doing most of merges these days)

**Comment by rhys-vdw** [comment]
@indeyets No problem. I saw this email but haven't gotten around to reviewing yet. Just having a look now...

So this provides a generic way to ping a knex instance to check if it's up. I've got a few questions...

> If ping method fails then connection will be destroyed from the pool. 

Where is the code that handles this? I can't see it... :-S

@zachary822:
> The original knex would throw an error saying "This socket has been ended by the other party".
> It does not happen with this commit.

How could this be the case? Wouldn't that only happen if you luckily called `ping` after the db went down, but before your next query?

> Sadly I don't have time to set up all the databases to run the tests. I would be glad if somebody could run them and confirm the merge.

There are no new tests. Tests do appear to be failing in Travis, but I'm not sure if it's related.

[This concerns me](https://github.com/vellotis/knex/blob/ft-pool2-ping-connection/src/client.js#L192-L198). Is it okay to say the database is working when a client does not provide a `ping` feature? I'd probably prefer an NYI or even just an undefined exception here, unless there is some reasoning for this.

Steps to getting this merged (with my apologies to @vellotis for delayed review):

 - Answer above questions for me.
 - Add support for every dialect.
 - Add tests for `ping` in all use cases.
 - Add documentation explaining the feature to users.

**Comment by zachary822** [comment]
I think it has something to do with [this](https://github.com/myndzi/pool2/blob/master/lib/pool.js#L86-L86) in Pool2. You can provide a ping function to pool2 for it to call when it needs to ping the database (haven't got around to seeing when it does ping the database). The default pool2 ping implementation looks like a noop.

**Comment by vellotis** [comment]
As I have a need to deal with knex again I merged current tgriesser master into it.
As well I would write these missing tests. To follow some good practise, under where should I write these tests?

**Comment by wubzz** [comment]
@vellotis @rhys-vdw From my understanding this will expose a ping method on the knex client to check if the connection is still valid? 

If so, then in regards to #1198 and its related issues, I would prefer and recommend that we use `Pool2` to handle this internally in knex instead of having the user manually run ping commands. 

Having default ping functions would be needed either way, so the functions created in the PR are still valid, might just need some tweaks. I'm just implying they would be better of used as defaults for `config.pool.ping` when it is undefined.

**Comment by vellotis** [comment]
@wubzz, you are correct. #1198 is really closely related to current PR. I ran to the same problem long time ago. And I'm willing to contrubute to solve this.

I would just need some advice where should I write the tests. So everyone could be happy to finally 

@rhys-vdw Pinging methods:
  - maria :white_check_mark:
  - mssql :grey_question:
```javascript
    @driver.Connection::connect( config, cb )
```
  - mysql/mysql2 :white_check_mark:
  - postgres :white_check_mark:
  - oracle :grey_question: 

    https://github.com/oracle/node-oracledb/blob/02f74fabf09f039030c502cef9d74093b440a46f/doc/api.md#connectionhandling
```javascript
    oracledb.getConnection( settings, cb )
```
  - strong-oracle :grey_question:

    https://github.com/oracle/node-oracledb/blob/02f74fabf09f039030c502cef9d74093b440a46f/doc/api.md#connectionhandling
```javascript
    oracle.connect( settings, cb )
```
  - sqlite3 :question: 
  - websql :x:  (Depracted since November 18, 2010)

@rhys-vdw @ "This concerns me". I don't see the actual reference any more as the reference is against master branch not commit. But I suppose that the problem is resolved by https://github.com/myndzi/pool2/blob/2130ba5162de17b9311228ef97d071f7739ab1ce/lib/resource-request.js what is the outcome of my discussion @ https://github.com/myndzi/pool2/issues/15

**Comment by wubzz** [comment]
@vellotis Talked this over in #1198 and currently the idea is:

- Add default `ping` method for *all* dialects
- Ping method can be overwritten by explicitly defining `config.pool.ping` as a function, otherwise always use the dialect default.

Have you tested the ping methods in your PR against cases such as killing the connection on the server side? My assumption was that running a `SELECT 1` query would be the most efficent ping test, but I could very well be wrong.

Example postgres with pgAdmin:

```javascript
knex.raw('SELECT version()')
.then(() => {
debugger; //pgAdmin -> server status -> kill all connections
return knex.raw('SELECT version()')
})
.then(() => {
})
.catch((err) => {
//Should not reach this point
});
```

**Pull request closed without merging**
