### PR TITLE
Allow joins to nest conditional statements

### PR DESCRIPTION
**Pull request by atiertant**
fix https://github.com/tgriesser/knex/issues/690

make this possible:
```
.leftOuterJoin('accounts', function () {
    this
      .on('users.id', 'account.user_id')
      .andOn(function () {
         this.on('users.state', '=', 'NULL');
         this.orOn('users.state', 'accounts.state');
      });
  });
```

### CODE REVIEW

**Comment by rhys-vdw** [comment]
@atiertant Awesome work. Just requires test and documentation and we can get this in a release.

**Comment by atiertant** [comment]
@rhys-vdw where could i add documentation ? didn't see this in CONTRIBUTING.md ...

**Comment by rhys-vdw** [comment]
Yeah, sorry, we need a pull request template. PRs need tests and docs. The
documentation is just index.html (which is the website).

**Comment by atiertant** [comment]
@rhys-vdw hope all is correct

**Comment by rhys-vdw** [comment]
@atiertant Thanks for following that up. Looks great. 👍

**Comment by rhys-vdw** [comment]
Just released this as knex 0.11.3

**Comment by tuhoojabotti** [comment]
Buh, I was just trying achieve this and I read the docs and I was like why isn't this working even though the docs say it should, but once I found these issues I realized it's a brand new feature.

**Comment by helios1138** [comment]
knex 0.11.9 - not working

**Comment by atiertant** [comment]
@helios1138 have you got a failling code?

**Comment by emaddoma** [comment]
My own attempt to use this failed.

```
q.innerJoin('account_meta_catalog', function() {
    this.on('account_meta_catalog.account_id','=','accounts.id');
    this.andOn(function(){
        this.on(knex.raw("(account_meta_catalog.catalog->'card'->>'has_medical_discount_plan')::boolean = true"));
        this.orOn(knex.raw("(account_meta_catalog.catalog->'card'->>'has_dental_discount_plan')::boolean = true"));
    });
});
```

Results in error "TypeError: listener must be a function"

**Pull request merged**
