### PR TITLE
Add charset for columns (MySQL)

### PR DESCRIPTION
**Pull request by kid-icarus**

### CODE REVIEW

**Comment by samholmes** [comment]
+1

**Comment by elhigu** [comment]
Sorry for not commenting here anything earlier. 

I think this would be fine if documentation is just moved to knex/documentation repository. Closing for now since its incomplete. Will be reopened and can be merged if completed .

**Comment by samholmes** [comment]
How is this not completed?

**Comment by elhigu** [comment]
@samholmes  please read the closing comment.

> I think this would be fine * if documentation is just moved to knex/documentation repository*. Closing for now since its incomplete. Will be reopened and can be merged if completed .

**Pull request closed without merging**
