### PR TITLE
Call to knex.migrate.currentVersion causes an error #2111

### LINKED ISSUE #2111: Call to knex.migrate.currentVersion causes an error
I use **knex.migrate** for DB-migrations , and after each migration I call `knex.migrate.currentVersion(migrationConfig)` to get the new version of DB. Passing a `migrationConfig` argument is possible, if the [documentation](http://knexjs.org/#Migrations-currentVersion) is correct.

But after updating knex to version `0.13.0` I get an error:

```
Unhandled rejection TypeError: Cannot read property 'hasTable' of undefined
    at Migrator._ensureTable (/home/user/projects/demo/node_modules/knex/lib/migrate/index.js:248:22)
    at Migrator._listCompleted (/home/user/projects/demo/node_modules/knex/lib/migrate/index.js:394:17)
    at Migrator.currentVersion (/home/user/projects/demo/node_modules/knex/lib/migrate/index.js:177:17)
    at mycli.knex.migrate.latest.then (/home/user/projects/demo/bin/cli.js:87:29)
    at tryCatcher (/home/user/projects/demo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/user/projects/demo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/user/projects/demo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/user/projects/demo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/user/projects/demo/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/user/projects/demo/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/user/projects/demo/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/user/projects/demo/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

After short debugging, I found, that the bug is caused by changes in this file (and line): https://github.com/tgriesser/knex/blame/master/src/migrate/index.js#L261

Old code:

```js
  // Lists all migrations that have been completed for the current db, as an
  // array.
  _listCompleted() {
    const { tableName } = this.config
```

New version

```js
  // Lists all migrations that have been completed for the current db, as an
  // array.
  _listCompleted(trx = this.knex) {
    const { tableName } = this.config
```

In old version there was no params for methos `_listCompleted`, in new version - there is a `trx` param. Old version of code always used `this.knex`, and new version use passed `trx` param first.

I don't know, why you have added this param, but this patch is the reason of this bug.

### PR DESCRIPTION
**Pull request by koistya**
Fix #2111

### CODE REVIEW

**Comment by Industrial** [comment]
Would love to see this change merged :-)

**Comment by elhigu** [comment]
@Industrial There is one test failing on node 0.12 and I would like to know why. It didn't look like a random failure. I haven't got time time to figure it out and this PR cannot be merged before it works.

Also if we go by the book with PRs, there should be test case included reproducing the original error, even though for this one I'm willing to make an exception.

**Comment by maxkoryukov** [comment]
I think it is not a bad moment to drop support for Node < 4

**Comment by elhigu** [comment]
I dropped node 0.12 from master... this probably needs rebase, before travis will notice that test configuration was changed.

**Comment by elhigu** [comment]
All the necessary node version tests were fine, so I'm merging this in.

**Pull request merged**
