### PR TITLE
CLI: Fix empty --version output

### PR DESCRIPTION
**Pull request by Saka7**
Currently, `--version/-V` output looks broken (empty output):

```sh
knex --version

Knex CLI version: 
Local Knex version: 
```

#3311

### CODE REVIEW

**Comment by kibertoad** [comment]
Thank you! Could you please add test for this? Look at https://github.com/tgriesser/knex/tree/master/test/cli for inspiration.

**Comment by kibertoad** [comment]
@Saka7 Please let me know if you'll need any help with writing a test!

**Comment by Saka7** [comment]
@kibertoad I've added a test for cli version, please check

**Comment by kibertoad** [comment]
Thanks!

**Pull request merged**
