### PR TITLE
added clearSelect and clearWhere to query builder

### PR DESCRIPTION
**Pull request by alechirsch**
Copy of #1907, this pull request has my account attached to the commits...

### CODE REVIEW

**Comment by elhigu** [comment]
If you have time to implement this for returning, limit, order by, join, group by, having, on,  would be awesome. Still it won't be super useful since one cannot get for example subquery builders from outside to cleanup parts of subquery (like removing order by from some subquery).

Anyways I'm inclining to accept this feature after all. Maybe we could add new section to documentation, which lists all clearing functions, so it would be clear which parts of query builder can be reset... 

Code looks look, only documentations seem to be missing.

**Comment by alechirsch** [comment]
I have added documentation for the feature please let me know if I missed anything. Adding to the docs is slightly confusing.

[https://github.com/knex/documentation/pull/24](https://github.com/knex/documentation/pull/24)

**Comment by alechirsch** [comment]
@elhigu I do not have the time right now to add the other clear methods, however it should be easy to do so with the private method _clearGrouping function that I added. Testing would be the most time consuming.

**Comment by elhigu** [comment]
thanks!

**Pull request merged**
