### PR TITLE
Pass migration config object as an argument to the migrations (V 2.0)

### PR DESCRIPTION
**Pull request by kibertoad**
Reuses some tests from https://github.com/tgriesser/knex/pull/2778 but implemented in a completely different way.

### CODE REVIEW

**Comment by kibertoad** [comment]
@elhigu Updated existing PR to make it mergeable; please let me know if something is missing, will address ASAP - would like to unblock https://github.com/tgriesser/knex/issues/2799

**Comment by elhigu** [comment]
I still think that knex should have more general solution which can be used to resolve also this issue.

**Comment by kibertoad** [comment]
Yeah, I will update this PR based on our discussion in the old PR.

**Comment by kibertoad** [comment]
https://github.com/knex/documentation/pull/135 -> documentation

**Comment by kibertoad** [comment]
> if withUserParams is called for transaction knex client. Maybe and error should be thrown

Should I check by this instanceof Transactor or there is a better way?

> Tests should also check that when transaction is created that user parameters can be accessed through that trx knex instance.

How is that different from existing `transaction of a copy with userParams retains userparams` test?

> (that could be implemented also later on I think)

I would appreciate that :). Stayed till 5 AM yesterday to finish this thing, need to recharge before I'll be able to do larger changes again.

**Comment by kibertoad** [comment]
@elhigu OK, changes for initial param support were surprisingly straightforward to implement, so I think all of your comments are covered now (as previously mentioned, there was a test for userParams in transaction already).

**Comment by elhigu** [comment]
This looks really promising, but I need to check this out when I'm less tired.

I might try to do some additional manual testing  by setting temporarily all knex test instances to be cloned instances to see that tests will work perfectly with those too :)

I also was worried that this could have been actually a lot harder to implement so that everything works fine after cloning, but I'm glad I was wrong. Great work 👍

**Comment by kibertoad** [comment]
@elhigu Well, admittedly, it did took a bit of black magic to get cloning exactly right, as we have a function which is also an object with getters, which is not that straightforward to clone, but fortunately JS is flexible enough. You are welcome!

**Comment by elhigu** [comment]
I got finally time to do some manual testing of this. 

I changed in suite.js passed knex instances to be cloned ones and some of the tests seem to be failing. Most of them seem to be related to knex.raw and maybe to postProcessResponse hook.

```
    require('./schema')(knex.withUserParams({}));
    require('./migrate')(knex.withUserParams({}));

    require('./seed')(knex.withUserParams({}));
    require('./builder/inserts')(knex.withUserParams({}));
    require('./builder/selects')(knex.withUserParams({}));
    require('./builder/unions')(knex.withUserParams({}));
    require('./builder/joins')(knex.withUserParams({}));
    require('./builder/aggregate')(knex.withUserParams({}));
    require('./builder/updates')(knex.withUserParams({}));
    require('./builder/transaction')(knex.withUserParams({}));
    require('./builder/deletes')(knex.withUserParams({}));
    require('./builder/additional')(knex.withUserParams({}));
    require('./datatype/bigint')(knex.withUserParams({}));
```

**Comment by kibertoad** [comment]
@elhigu thanks, will take a look today!

**Comment by kibertoad** [comment]
@elhigu OK, I've addressed everything that looked like genuine problems - remaining ones look like they are related to some isolation between different copies happening (different transactions?) that doesn't look like something worth spending effort on resolving, as I'm not even sure that it's an invalid behaviour, and user is not really supposed to expect different copies of knex to run in single transaction (you even requested explicitly to forbid transaction copying). If you run

```
const knexCopy = knex.withUserParams({});
require('./schema')(knexCopy);
    require('./migrate')(knexCopy);

    require('./seed')(knexCopy);
    require('./builder/inserts')(knexCopy);
    require('./builder/selects')(knexCopy);
    require('./builder/unions')(knexCopy);
    require('./builder/joins')(knexCopy);
    require('./builder/aggregate')(knexCopy);
    require('./builder/updates')(knexCopy);
    require('./builder/transaction')(knexCopy);
    require('./builder/deletes')(knexCopy);
    require('./builder/additional')(knexCopy);
    require('./datatype/bigint')(knexCopy);
```

it seems to pass fine now.

**Comment by kibertoad** [comment]
Woohoo, the odyssey is over now!

**Comment by elhigu** [comment]
Thanks! I'll make new `@next` release with this soon.

**Comment by kibertoad** [comment]
Thank you! Any chance https://github.com/tgriesser/knex/pull/2817 could also get in if there is nothing wrong with the implementation? (I'll resolve conflict in a couple of minutes)

**Comment by elhigu** [comment]
I think this + babel update together might have broken something

**Comment by kibertoad** [comment]
I can totally look into it right now, what's the problem and how I can reproduce?

**Comment by elhigu** [comment]
This one suggests https://www.npmjs.com/package/babel-preset-eslatest-node6 to use https://babeljs.io/docs/en/babel-polyfill/ for that support. Seems a bit more trustworthy.

**Comment by kibertoad** [comment]
Right. Will add it now

**Comment by kibertoad** [comment]
https://github.com/tgriesser/knex/pull/2821

**Pull request merged**
