### PR TITLE
Create If Not Exists

### PR DESCRIPTION
**Pull request by henrygiocondo**
The IF condition was wrote wrong, instead of 'create if not exists' it was 'create if exists'

### CODE REVIEW

**Comment by rhys-vdw** [comment]
Any chance we could get a test for this one?

**Comment by henrygiocondo** [comment]
How do i? Im using my correction on MSSQL and its ok... its just a logic
case... object_id returns the id of the table, so, it was checkin if
object_id is not null to create, if it is not null then it already exists
on the database...

I just changed it to object_id is null (the object does not exists on the
db) so create.

If you need a test just tell me how to do.


2016-01-18 20:40 GMT-02:00 Rhys van der Waerden <notifications@github.com>:

**Comment by rhys-vdw** [comment]
@henrygiocondo, I just noticed that you've modified the wrong file. You must edit the file under `/src`, not `/lib`. `/lib` is generated from `/src` by Babel.

Also, if you don't mind doing the test, just add this case to this file: https://github.com/tgriesser/knex/blob/master/test/unit/schema/mssql.js

Thanks. :+1:

**Comment by henrygiocondo** [comment]
I changed the file on src and created the test case. Closing

**Pull request closed without merging**
