### PR TITLE
Jsonb type to schema.

### PR DESCRIPTION
**Pull request by elhigu**
Fix for issue #991

### CODE REVIEW

**Comment by elhigu** [comment]
@rhys-vdw / @tgriesser comments to this?

**Comment by rhys-vdw** [comment]
Hey @elhigu. Could you please remove references to the `jsonb` bool argument to `schema.json()` documentation, and add a deprecation message if it is supplied?

**Comment by rhys-vdw** [comment]
Otherwise looks great.

**Comment by elhigu** [comment]
Great, I'll fix / update pull request tomorrow.

**Comment by elhigu** [comment]
Aand now this is fixed, no more documentation about `json(true)` and added deprecation message.. I also added sent fixes for #662 and #1003

**Comment by elhigu** [comment]
@rhys-vdw I updated this pull request few days ago with suggested changes... would it be ok now to be merged?

**Comment by rhys-vdw** [comment]
Hey @elhigu, just hadn't gotten around to the review. Looks good.

**Pull request merged**
