### PR TITLE
Fix broken import in knex.js

### PR DESCRIPTION
**Pull request by timwis**
Unless I've misread, I think this link is broken.

### CODE REVIEW

**Comment by elhigu** [comment]
Looks like our build system is having some serious problems...

**Comment by elhigu** [comment]
I suppose that this is not a bug. As far as I know this file is not compiled.

**Comment by timwis** [comment]
Huh? `package.json`'s `main` property points to `knex.js`. `knex.js` exports `./lib/index`, which doesn't exist. How is that not broken?

**Comment by tgriesser** [comment]
It exists when the lib is babel compiled, check the node_modules files when it's installed from npm

**Comment by timwis** [comment]
Ah! Thought I was going crazy there.. thanks!

**Pull request closed without merging**
