### PR TITLE
Don't die when pg client emits error

### PR DESCRIPTION
**Pull request by myndzi**

### CODE REVIEW

**Comment by myndzi** [comment]
These tests are super whack. "sqlite3 dropTable has a dropTableIfExists method" -- dialects/postgres/index ???

I don't even know how to approach this.

**Comment by myndzi** [comment]
There. The 'end' event may not be necessary, but I don't know enough about the inner guts of knex to really track that down. Tests pass, and forcing an error event via pg_terminate_backend doesn't bother my connection test script one bit.

**Comment by bendrucker** [comment]
Will do my best to make time for this sometime this week

**Comment by myndzi** [comment]
Do not merge this just yet. There's an outstanding issue causing connection leaks(!)

The fix is either in generic-pool-redux (ensure count is adjusted only by successfully destroyed objects) or in this patch (validate/synchronize pool destroy requests to ensure invalid or already-removed things aren't called)

The former makes more sense to me, and I'm uncertain how to correctly perform the latter.

**Comment by myndzi** [comment]
Incompatible with https://github.com/tgriesser/knex/pull/693

When the above is added, will re-submit this one.

**Comment by bendrucker** [comment]
Is this good to merge now?

**Comment by tgriesser** [comment]
Doesn't look like it, still referencing `genericPool`

**Comment by myndzi** [comment]
It wasn't synching up with my origin branch, so the change didn't get pushed; I rebased it onto upstream/master and force-pushed.

**Comment by bendrucker** [comment]
If you can do a second rebase and get these squashed into a single commit this seems good to merge

**Comment by myndzi** [comment]
Okay.

**Comment by bendrucker** [comment]
Done! Thanks for your help on this

**Pull request closed without merging**
