### PR TITLE
cli --config new option supporting the old --knexfile, or a connection string

### PR DESCRIPTION
**Pull request by caub**
It allows to pass now a connection-string directly via cli, example in package.json scripts:

```json
    "db:init": "knex --config ${DB_URL-'pg://tz@localhost/tz'} migrate:latest",
```

it works with a config file as well, like before:

```json
    "db:init": "knex --config .db-config.js migrate:latest",
```

and defaults to `.knexfile.js` at the project root, when it exists

```json
    "db:init": "knex migrate:latest",
```

### CODE REVIEW

**Comment by caub** [comment]
@elhigu sorry to disturb you, how you go about testing the cli?

Else I'm going to push the documentation and examples, I think this PR makes thing more practical, I reused https://github.com/tgriesser/knex/pull/2300 which adds a default knexfile path

**Comment by elhigu** [comment]
@caub there is currently no tests for the `cli.js` file, which is the biggest problem. It probably needs some completely new test directory with some config files etc. for running the client.

**Comment by caub** [comment]
I've started some tests, but it's not easy

```diff
diff --git a/test/index.js b/test/index.js
index e3285d3..1f0dd05 100644
--- a/test/index.js
+++ b/test/index.js
@@ -31,7 +31,6 @@ describe('Query Building Tests', function() {
   require('./unit/schema/oracledb')
   require('./unit/migrate/migrator')
   require('./unit/seed/seeder')
-  require('./unit/cli')
 })
 
 describe('Integration Tests', function() {
diff --git a/test/unit/cli/index.js b/test/unit/cli/index.js
deleted file mode 100644
index aacc24d..0000000
--- a/test/unit/cli/index.js
+++ /dev/null
@@ -1,12 +0,0 @@
-var cp = require('child_process');
-var assert = require('assert');
-
-describe("CLI Unit Tests", function() {
-
-  it('Displays help with no arguments', function() {
-    
-    var output = cp.execSync(__dirname + '/node_modules/.bin/knex --config').toString();    
-    // console.log(output);
-    assert(/Usage: knex \[options\] \[command\]/.test(output));
-  });
-});
diff --git a/test/unit/cli/knexfile.js b/test/unit/cli/knexfile.js
deleted file mode 100644
index f2702de..0000000
--- a/test/unit/cli/knexfile.js
+++ /dev/null
@@ -1,3 +0,0 @@
-module.exports = {
-  connection: 'pg://postgres@localhost/knex_test'
-};
diff --git a/test/unit/cli/package.json b/test/unit/cli/package.json
deleted file mode 100644
index b745e7a..0000000
--- a/test/unit/cli/package.json
+++ /dev/null
@@ -1,8 +0,0 @@
-{
-  "description": "knex cli test",
-  "repository": "../..",
-  "license": "MIT",
-  "dependencies": {
-    "knex": "file:../../.."
-  }
-}
```

If people want to test/use already this new CLI changes now, they can use https://gist.github.com/caub/a8c23f97aa1942f2012ad8639769168c

**Comment by kibertoad** [comment]
I think this is already currently handled by `--client` and `--connection` flags in CLI. Feel free to reopen it if I'm wrong.

**Pull request closed without merging**
