### PR TITLE
Add collate for columns (MySQL)

### PR DESCRIPTION
**Pull request by alexrsagen**
This had been requested in #599 a year ago, but a PR was never created.

I have included a test that passed when i ran it.

### CODE REVIEW

**Comment by alexrsagen** [comment]
@rhys-vdw Please have a look at this.

**Comment by meepdarknessmeep** [comment]
very useful please add

**Comment by tjwebb** [comment]
@alexrsagen can you add docs for this feature? Otherwise, lgtm

**Comment by alexrsagen** [comment]
@tjwebb Is this okay? 2fae475

**Comment by alexrsagen** [comment]
I have no idea how that one check failed, but i'm sure i didn't touch that, and the only thing i just changed was index.html... It said it timed out, so must be slow vm or old Node.js version causing that.

**Comment by elhigu** [comment]
I re-triggered the test :) it was just usual timeout when some test doesn't complete in 5000ms... Not sure if there is real problem in somewhere in our codebase or is it just random lagging of travis, which causes it. It happens maybe once in every 20 build or so.

**Comment by alexrsagen** [comment]
@elhigu Great, thanks :)

I think the timeout issue is more than likely a problem with travis, as they create a very small VM or container for every test they run, so they can't use many resources.

Could you or another collaborator merge this please? Currently i'm using `table.string("email").comment("' collate 'utf8_unicode_ci")` to get past without the function i'm committing here :)

**Comment by elhigu** [comment]
@alexrsagen code looks fine to me. We are trying to push out 0.10 so I would rather merge this after it is released... we hope to be able to make releases in faster cycle in future.

**Comment by alexrsagen** [comment]
@elhigu Ah i see. Thanks for clarifying :)

**Pull request merged**
