### PR TITLE
Pass migration config object as an argument to the migrations themsel…

### PR DESCRIPTION
**Pull request by dofrisec**
…ves, to allow custom parameters to be set for migrations. (#2014)

### CODE REVIEW

**Comment by dofrisec** [comment]
Associated documentation update:
https://github.com/knex/documentation/pull/130

**Comment by dofrisec** [comment]
I updated the migration stubs that were obvious, all except the typescript stub.
I'm not sure what to do with the typescript migration stub, since I'm not familiar with typescript.

**Comment by kibertoad** [comment]
This would also be helpful for the https://github.com/tgriesser/knex/issues/2799 use-case. @elhigu Do you approve of this idea in general? There's a minor conflict to be resolved before this could be merged, but at this point it's unclear if it's worth doing so.

**Comment by kibertoad** [comment]
@elhigu I think all use-cases are going to be about parametrizing migration execution from the outside. If these should be set through knex instance itself, I think we should define a recommended way to do it (e. g. have precreated knex.locals empty object for population) and document it. If you think that this is a better way, I can do both the code and the documentation change.

**Comment by elhigu** [comment]
> @elhigu I think all use-cases are going to be about parametrizing migration execution from the outside. If these should be set through knex instance itself, I think we should define a recommended way to do it (e. g. have precreated knex.locals empty object for population) and document it. If you think that this is a better way, I can do both the code and the documentation change.

I like something like knex.locals or even more descriptive knex.userParams more. That would be more versatile solution that could work for more things than just migrations and initial values for those already in knex configuration.

**Comment by dofrisec** [comment]
Wouldn't that have race conditions?

> > @elhigu I think all use-cases are going to be about parametrizing migration execution from the outside. If these should be set through knex instance itself, I think we should define a recommended way to do it (e. g. have precreated knex.locals empty object for population) and document it. If you think that this is a better way, I can do both the code and the documentation change.
> 
> I like something like knex.locals or even more descriptive knex.userParams more. That would be more versatile solution that could work for more things than just migrations. Initial attributes for that object could be given already in knex configuration.

Wouldn't that have race conditions?

**Comment by elhigu** [comment]
> > > @elhigu I think all use-cases are going to be about parametrizing migration execution from the outside. If these should be set through knex instance itself, I think we should define a recommended way to do it (e. g. have precreated knex.locals empty object for population) and document it. If you think that this is a better way, I can do both the code and the documentation change.
> > 
> > 
> > I like something like knex.locals or even more descriptive knex.userParams more. That would be more versatile solution that could work for more things than just migrations. Initial attributes for that object could be given already in knex configuration.
> 
> Wouldn't that have race conditions?

Not that I can think of. Why would it?

**Comment by kibertoad** [comment]
Imagine typicaly multi-tenancy scenario: you have independent schemas that can be migrated totally independently. You run their migrations in the loop, setting params on same knex instance. It is totally possible that you will run start migrations for schema 2 while only 77 out of 100 migrations for schema 1 passed, then migration 78 for schema 1 will suddently be executed with params for schema 2.
You can obviously await till schema 1 is done before starting with schema 2, but this means we have more limitations and gotchas that we could have with better isolation (e. g. passing params to migration itself rather than knex).

**Comment by elhigu** [comment]
> Imagine typical multi-tenancy scenario: you have independent schemas that can be migrated totally independently. You run their migrations in the loop, setting params on same knex instance. It is totally possible that you will run start migrations for schema 2 while only 77 out of 100 migrations for schema 1 passed, then migration 78 for schema 1 will suddenly be executed with params for schema 2.
> You can obviously await till schema 1 is done before starting with schema 2, but this means we have more limitations and gotchas that we could have with better isolation (e. g. passing params to migration itself rather than knex).

Ah right, that use case where migrations are ran like that. Yep, something should be thought to address that. 

I was thinking at some point something like knex.userParams({}) which would return kind of instance of knex, using the same pool, but there would be different user parameter set assigned to that "instance".

I'm not sure at all what would be the best solution and API (I know only that I don't want it to be specific functionlity for migrations only).

**Comment by kibertoad** [comment]
Ah, that might work - will try to update existing PR to use the kind of implementation that you are suggesting.

**Comment by kennedyvardo** [comment]
Is that option of passing parameters already implemented?

**Comment by elhigu** [comment]
Yes. https://knexjs.org/#Installation-parametrization

**Pull request closed without merging**
