### PR TITLE
native promises

### PR DESCRIPTION
**Pull request by danielgatis**

### CODE REVIEW

**Comment by kibertoad** [comment]
@danielgatis What is the rationale behind this change?

**Comment by danielgatis** [comment]
It was a experiment and I want to run the tests to collect some information. I will close this pull asap.

**Comment by elhigu** [comment]
@kibertoad to get rid of unnecessary dependency mostly. Bluebird is not anymore that indispensable that it was couple years ago. Also after async / await world it is all the time less useful, since for example even if you return bluebird promise from `async` function, it will be wrapped to native promise because of `async` declaration.

**Comment by kibertoad** [comment]
@elhigu Isn't bluebird still much more performant than native promises? (less so on newer Node.js version, but still).

**Comment by elhigu** [comment]
@kibertoad performance difference is nowadays pretty irrelevant. I would be surprised if native implementation would not be faster (if it isn't yet) at some point. Anyways as said it is irrelevant. Both are fast enough.

**Comment by danielgatis** [comment]
The main goal behind this is to make the use of transactions easier with the use of async hooks.

**Pull request closed without merging**
