### PR TITLE
Do not reject promise on transaction rollback

### LINKED ISSUE #3246: Transaction rollback cause unhandled rejection
Example code:

```js
const knex = require('knex')(/* config */);

process.on('unhandledRejection', err => {
    console.log('unhandled!');
    console.log(err);
});

async function test() {
    const trx = await knex.transaction();
    await trx.rollback();
    console.log('OK');
}

test();
```

Output:

```log
03:15:36.907 info: OK
03:15:36.915 error: Transaction rejected with non-error: undefined
03:15:36.915 info: unhandled!
03:15:36.917 info: Transaction rejected with non-error: undefined
```

I can not define error handler cause `.transaction()` returns `trx.initPromise`.
https://github.com/tgriesser/knex/blob/master/src/util/make-knex.js#L41-L52

My temporary workaround:
```js
const trx = await new Promise(resolve => 
    knex.transaction(trx => 
        resolve(trx)
    ).catch(() => {})
);
```

### PR DESCRIPTION
**Pull request by kibertoad**
fixes #3246

### CODE REVIEW

**Comment by kibertoad** [comment]
@elhigu I've updated implementation to have explicit checks that we actually were rollbacking ourselves. What do you think?

**Comment by elhigu** [comment]
Sounds like a good idea! I didn’t see any problems with code either. 👍

I should write out some tests which actually tests what happens in knex  In different dialects when query throws e.g. conflict error inside transaction which is not leaked out of handler and not causing knex side rollback. Currently I know only more or less what pg dialect does in that case.

**Comment by kibertoad** [comment]
Does that need to happen in this pr?

**Comment by elhigu** [comment]
> Does that need to happen in this pr?

no, thats why I said `I should...`, I just have personal interest to know how knex really behaves in those cases with other drivers.

**Comment by kibertoad** [comment]
@elhigu Thought so, but clarified just in case, as you didn't approve PR either :-D

**Comment by kibertoad** [comment]
Ahaha, yeah, mobile version is a mess. Thanks!

**Pull request merged**
