### PR TITLE
Code cleanup (trimmed trailing spaces & removed tabs)

### PR DESCRIPTION
**Pull request by jurko-gospodnetic**
Trimmed trailing spaces & converted some tabs to spaces to maintain code consistency.

### CODE REVIEW

**Comment by jurko-gospodnetic** [comment]
The only tests currently reported as failing are completely random - due to some unrelated and badly written test code that did not expect to be running on a database system performant enough to finish its query before its 1 ms timeout kicked in.

Same effect noticed on pull request #1257.

**Comment by wubzz** [comment]
@jurko-gospodnetic Yea, that test has come back to bite us in the ass more than once. It's a bit tricky to make an integration test across all dialects for it. Currently it seems only postgres is failing from time to time. Will try to adjust the insert query for postgres specifically, unless you have a better proposal.

I've rerun the build on your pull requests for now.

**Comment by jurko-gospodnetic** [comment]
Well, you can use `pg_sleep()` in that query for Postgres to make it sleep a given number of seconds. Not portable, but will get the immediate issue out of the way.

**Comment by wubzz** [comment]
@jurko-gospodnetic See attempts in #1260 .

Thanks for the PR btw, merging this.

**Pull request merged**
