### PR TITLE
Rename src directory to lib

### PR DESCRIPTION
**Pull request by ricardograca**
This restores backwards compatibility with versions before 0.18 if you were importing sub-packages directly, e.g. `lib/query/builder`. This technique is used when mocking certain parts of the Knex API for testing other applications that use Knex. 

Link to discussion: https://github.com/bookshelf/bookshelf/pull/1988

Note that there are no drawbacks to this change, other than breaking backwards compatibility again for people that could have used the same technique for versions 0.18.0-0.18.3, but considering this was released a couple of weeks ago this scenario is unlikely.

The idea here is to maintain the internal structure of the files available in the released build as in previous versions.

### CODE REVIEW

**Comment by elhigu** [comment]
Please check also if documentation repo needs changes when it builds knex. Some stub requires might need fixing.

**Comment by ricardograca** [comment]
Will do.

**Comment by ricardograca** [comment]
I checked and I can't find any reference to `/src` in the docs. I tried building it and it seemed to generate the docs correctly despite this error:

```
Building docs for production
[docs-server]  /home/ricardo/src/knex-documentation/node_modules/babel-core/lib/transformation/file/index.js:558
[docs-server]        throw err;
[docs-server]        ^
[docs-server]  
[docs-server]  SyntaxError: /home/ricardo/src/knex/lib/migrate/Migrator.js: Unexpected token (43:10)
[docs-server]    41 |       if (!knex.isTransaction) {
[docs-server]    42 |         this.knex = knex.withUserParams({
[docs-server]  > 43 |           ...knex.userParams,
[docs-server]       |           ^
[docs-server]    44 |         });
[docs-server]    45 |       } else {
[docs-server]    46 |         this.knex = knex;
[docs-server]      at Parser.pp$5.raise (/home/ricardo/src/knex-documentation/node_modules/babylon/lib/index.js:4454:13)
[docs-server]      at Parser.pp.unexpected (/home/ricardo/src/knex-documentation/node_modules/babylon/lib/index.js:1761:8)
[docs-server]      at Parser.pp$3.parseIdentifier (/home/ricardo/src/knex-documentation/node_modules/babylon/lib/index.js:4332:10)
[docs-server]      at Parser.pp$3.parsePropertyName (/home/ricardo/src/knex-documentation/node_modules/babylon/lib/index.js:4156:96)
[docs-server]      at Parser.pp$3.parseObj (/home/ricardo/src/knex-documentation/node_modules/babylon/lib/index.js:4045:12)
[docs-server]      at Parser.pp$3.parseExprAtom (/home/ricardo/src/knex-documentation/node_modules/babylon/lib/index.js:3719:19)
[docs-server]      at Parser.pp$3.parseExprSubscripts (/home/ricardo/src/knex-documentation/node_modules/babylon/lib/index.js:3494:19)
[docs-server]      at Parser.pp$3.parseMaybeUnary (/home/ricardo/src/knex-documentation/node_modules/babylon/lib/index.js:3474:19)
[docs-server]      at Parser.pp$3.parseExprOps (/home/ricardo/src/knex-documentation/node_modules/babylon/lib/index.js:3404:19)
[docs-server]      at Parser.pp$3.parseMaybeConditional (/home/ricardo/src/knex-documentation/node_modules/babylon/lib/index.js:3381:19)
[docs-server]      at Parser.pp$3.parseMaybeAssign (/home/ricardo/src/knex-documentation/node_modules/babylon/lib/index.js:3344:19)
[docs-server]      at Parser.pp$3.parseExprListItem (/home/ricardo/src/knex-documentation/node_modules/babylon/lib/index.js:4312:16)
[docs-server]      at Parser.pp$3.parseCallExpressionArguments (/home/ricardo/src/knex-documentation/node_modules/babylon/lib/index.js:3573:20)
[docs-server]      at Parser.pp$3.parseSubscripts (/home/ricardo/src/knex-documentation/node_modules/babylon/lib/index.js:3533:31)
[docs-server]      at Parser.pp$3.parseExprSubscripts (/home/ricardo/src/knex-documentation/node_modules/babylon/lib/index.js:3504:15)
[docs-server]      at Parser.pp$3.parseMaybeUnary (/home/ricardo/src/knex-documentation/node_modules/babylon/lib/index.js:3474:19)
```

I'll fix the conflicts now.

**Comment by kibertoad** [comment]
@ricardograca Thank you! I will be releasing 0.18.4 today, and after that will merge the PR to 0.19.0 if PR is ready.

**Comment by ricardograca** [comment]
Thanks! I just fixed the conflicts. You can ping me if there are more in the mean time.

**Comment by kibertoad** [comment]
Nope, seems to be just fine. I'll wait for CI to complete and then merge it. Thank you again!

**Comment by ricardograca** [comment]
Thanks! I didn't realize that was just an example in the `UPGRADING.md` file :sweat_smile:

**Comment by ricardograca** [comment]
There seems to be one error in the test suite when running in Node 8. This wasn't happening before. Is it a known issue?

**Comment by kibertoad** [comment]
@ricardograca Difficult to check logs on mobile, but wasn't it https://github.com/tgriesser/knex/issues/3225?

**Comment by elhigu** [comment]
All seem to pass in master at least.

**Comment by ricardograca** [comment]
@kibertoad I restarted the job and then deleted the branch (oops) so I can't see the original log or re-run the test, but it was one test complaining that an array of length 1 was expected but got 0.

In any case, if `master` passes it's all that matters.

**Pull request merged**
