### PR TITLE
fixed table alter attributes order. (first, after)

### PR DESCRIPTION
**Pull request by why2pac**
Fixed issue, #1946

Should first and after attributes are placed after comment attribute.

### CODE REVIEW

**Comment by why2pac** [comment]
@elhigu I added 2 test cases. At after position with comment and at first position with comment.

**Comment by elhigu** [comment]
Thanks for adding unit tests, but there should be still integration test which uses real DB. Checking only which kind of query is generated is not enough.

https://github.com/tgriesser/knex/blob/master/CONTRIBUTING.md

**Comment by why2pac** [comment]
@elhigu I added real database test cases.

**Comment by elhigu** [comment]
@why2pac awesome, thanks!

**Comment by why2pac** [comment]
@elhigu Thanks!

**Pull request merged**
