### PR TITLE
chore: clone only the last 5 commits

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by kibertoad** [comment]
What are the downsides of cloning everything?

**Comment by DanielRuf** [comment]
> What are the downsides of cloning everything?

The default is `50` which takes longer.

**Comment by kibertoad** [comment]
Can you elaborate on what are the downsides of not cloning 50?..

**Comment by DanielRuf** [comment]
> the downsides of not cloning 50

Downsides? Both are shallow clones. 5 commits are sufficient as no time traveling is needed.

See https://docs.travis-ci.com/user/customizing-the-build#Git-Clone-Depth

**Comment by DanielRuf** [comment]
Build time might go down with consecutive builds and the other PRs, will keep an eye on them and reevaluate and check the results with the CI env.

**Comment by elhigu** [comment]
Sorry, I fail to see any realworld benefit in this change, builds are already really slow.

**Comment by DanielRuf** [comment]
Well ok. In general we could still improve it further =)

**Pull request closed without merging**
