### PR TITLE
Test branch to try to trace failure in travis ci (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by elhigu**
DO NOT MERGE THIS

### CODE REVIEW

**Comment by elhigu** [comment]
Looks like the reason for random fails really is travis lagging it takes anything from 2 - 5 minutes to run tests there. So fix for this will be to add TEST_TIMEOUT environment variable to allow set it to 30 - 60000 when running tests in CI.

**Comment by rhys-vdw** [comment]
@elhigu Did you open an issue/PR to add timeout to CI?

**Comment by elhigu** [comment]
@rhys-vdw nope, I just left this open on my screen to implement this after work

**Comment by rhys-vdw** [comment]
👍

**Comment by elhigu** [comment]
aandfixed... hope that PR doesn't timeout :D https://github.com/tgriesser/knex/pull/1498

**Pull request closed without merging**
