### PR TITLE
Accept `timezone` config option in mysql2 dialect

### PR DESCRIPTION
**Pull request by necaris**

### CODE REVIEW

**Comment by rhys-vdw** [comment]
You must change files in the src folder, the changes you've made will be
overridden when compiled.

**Comment by necaris** [comment]
Thanks

--
Rami Chowdhury
"Be the change you wish to see in the world." -- Mahatma Gandhi
+1-408-372-6496 / +44-7581-430517 / +88-1778-986280

**Comment by jtwebman** [comment]
I did this with pull request https://github.com/tgriesser/knex/pull/980 and added all the missing ones.

**Comment by elhigu** [comment]
Fixed by #980

**Pull request closed without merging**
