### PR TITLE
Fixing issue with add columns on tables failing if using both after and collate

### PR DESCRIPTION
**Pull request by tmeinders**

### CODE REVIEW

**Comment by kibertoad** [comment]
@tmeinders How difficult would it be to add a test?

**Comment by tmeinders** [comment]
I'd be happy to make some tests. At the moment though, I've not been able to get the tests running smoothly. I run into this right now and haven't had a chance to dig into it:
```
Knex:warning - Connection Error: Connection ended unexpectedly
Knex:warning - Connection Error: Connection ended unexpectedly
                ✓ connection pool can query x10 (43ms)
>> Destroying container
#~ Stopped container c081510155435ce7aa53e2d4ca27e05fe1eda19a4fe4f468be37c936ab16ae69
#~ Removed container c081510155435ce7aa53e2d4ca27e05fe1eda19a4fe4f468be37c936ab16ae69

  mariadb | mariasql
Knex:warning - Connection Error: Error: Can't connect to MySQL server on '127.0.0.1' (61 "Connection refused")
Knex:warning - Connection Error: Error: Can't connect to MySQL server on '127.0.0.1' (61 "Connection refused")
    1) "before all" hook

  760 passing (3m)
  1 failing

  1) mariadb | mariasql "before all" hook:
     select * from information_schema.tables where table_name = 'knex_migrations_lock' and table_schema = database() - Can't connect to MySQL server on '127.0.0.1' (61 "Connection refused")
  Error: Can't connect to MySQL server on '127.0.0.1' (61 "Connection refused")
```

If you know off the top of your head what might resolve this, let me know.

**Comment by elhigu** [comment]
Do you have mariadb/mysql running with root user withoit password and with knex_test database created? Also you can choose to which dbs run the tests wit DB environment parameter. Check for example travis configuration file.

**Comment by tmeinders** [comment]
Ah I was making some incorrect assumptions about docker's use in these tests. I was able to add a couple tests and run them against my own mysql setup. Let me know if there is anything to be improved for these tests (organizational or coverage).  If there is a guide to point me to for running and adding tests to satisfy pull requests for this project, I'll happily comply. Thanks for the support so far!

**Comment by elhigu** [comment]
Perfect. Thank you!

**Pull request merged**
