### PR TITLE
propagate pg stream errors

### PR DESCRIPTION
**Pull request by kturney**
fixes https://github.com/tgriesser/knex/issues/948

### CODE REVIEW

**Comment by kturney** [comment]
a downside I'm not sure how to address: the error causes Bluebird to log an unhandled exception message if the consuming code is only listening to the stream.

**Comment by rhys-vdw** [comment]
Looks good. These events should be propagated.

> the error causes Bluebird to log an unhandled exception message if the consuming code is only listening to the stream.

Without using the callback argument you mean?

**Comment by kturney** [comment]
@rhys-vdw yes, the log shows up when using the returned stream. You can see an example in the test run: https://travis-ci.org/tgriesser/knex/jobs/122960719#L1630

**Comment by tgriesser** [comment]
Sounds like a good change, if you want to resolve the conflicts I will merge and get this into the next minor bump... If not let me know and I can add this manually

**Comment by kturney** [comment]
build failed because of timeouts, but I'm not seeing a retry/rebuild button

**Comment by elhigu** [comment]
Fixed in https://github.com/tgriesser/knex/pull/2199

**Pull request closed without merging**
