### PR TITLE
Support question mark escaping for knex rendered queries

### PR DESCRIPTION
**Pull request by elhigu**
Fixes bug in #519 by adding more complete support for `\?` escape sequence

### CODE REVIEW

**Comment by rhys-vdw** [comment]
Specific comment [here](https://github.com/tgriesser/knex/issues/519#issuecomment-156168563).

**Comment by rhys-vdw** [comment]
I'm thinking of merging #886, which I believe would conflict with this change. Are you happy to retarget the changes afterwards?

**Comment by elhigu** [comment]
@rhys-vdw, sure of course :) I fixed conflicts.

**Comment by elhigu** [comment]
@rhys-vdw looks like there has been no activity in #886. Maybe this could be already merged?

**Comment by rhys-vdw** [comment]
Yep, looks good to be @elhigu. Cheers. :+1:

**Pull request merged**
