### PR TITLE
stop executing tests on Node 4 and 5, update documentation.

### PR DESCRIPTION
**Pull request by igor-savin-ht**

### CODE REVIEW

**Comment by igor-savin-ht** [comment]
Related to #2450

**Comment by igor-savin-ht** [comment]
@elhigu Given that no code was changed, I presume that failure is due to flaky tests. Is there a way to trigger tests again, or should I just make a dummy commit.

**Comment by pablopen** [comment]
I hope you dont drop support for node 4. I know it only has 2 months left for LTS, but it's really neccessary?

**Comment by elhigu** [comment]
Lets apply this a bit later when when node 4 LTS period ends.

**Comment by capaj** [comment]
@igor-savin-ht let's add engines to package.json while we're at it: https://github.com/igor-savin-ht/knex/pull/1

**Comment by igor-savin-ht** [comment]
@capaj Will do!

**Comment by igor-savin-ht** [comment]
@elhigu Considering that 0.15 is incoming, probably now is the good time to merge this?

**Comment by kibertoad** [comment]
@elhigu Given that tests pass and linting pass, any ideas why build on Node 6 could have failed?..

**Comment by elhigu** [comment]
`Segmentation fault (core dumped)` I've seen that every now and then. I don't know where it comes, I just hit restart button for node 6.

**Pull request merged**
