### PR TITLE
Prepare for 0.16.4-next3 release

### PR DESCRIPTION
**Pull request by kibertoad**

### CODE REVIEW

**Comment by elhigu** [comment]
I've been also fixing locally tests and stuff for next release... there are some bugs still to be fixed before the release.

**Comment by kibertoad** [comment]
@elhigu Are these new bugs that would be regression compared to 0.16.3?

**Comment by elhigu** [comment]
Yep. All tests were working on 0.16.3

**Comment by kibertoad** [comment]
@elhigu Merging the changes, but will wait with release for now.

**Comment by elhigu** [comment]
Can be released already, I can push those test related changes in later on 👍

**Pull request merged**
