### PR TITLE
chore: cache node_modules

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by kibertoad** [comment]
What are the benefits of this?

**Comment by DanielRuf** [comment]
It caches the `node_modules` and is partly an alternative to `npm ci`. If there is a cache with the same deps it will load the cache instead of installing all deps again = faster builds.

**Comment by kibertoad** [comment]
Hell yeah, difference seems to be quite noticeable.

**Comment by DanielRuf** [comment]
Can be probably better in combination with the other PRs and with following builds / PRs.

Unfortunately the env is not the best for all cases https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System

**Comment by elhigu** [comment]
This seems like a good idea 👍 I have experienced issues with CI npm caches earlier (not updating to new versions to libs properly etc.), but I think we can give this a shot to see if there are any drawbacks this time (I have never used travis cache).

**Comment by elhigu** [comment]
thanks!

**Comment by DanielRuf** [comment]
> This seems like a good idea 👍 I have experienced issues with CI npm caches earlier (not updating to new versions to libs properly etc.), but I think we can give this a shot to see if there are any drawbacks this time (I have never used travis cache).

If this cache strategy creates any problems we can also try `$HOME/.npm` as alternative. So fr I saw no issues with the current cache strategy.

**Pull request merged**
