### PR TITLE
Fix native enum with specified schema (#3307)

### PR DESCRIPTION
**Pull request by Saka7**
# Fixes issue: #3307

## Current behaviour:

```javascript
knex
      .schemaBuilder()
      .withSchema('test')
      .table('users', function(table) {
        table
          .enu('foo', ['bar', 'baz'], {
            useNative: true,
            enumName: 'foo_bar',
          })
      })
      .toSQL();
```

## Outputs:
```sql
-- ...
create type "foo_bar" as enum ('bar', 'baz');
alter table "test"."users" add column "foo" "foo_bar";
-- ...
```

Schema builder doesn't take into account `withSchema` expression and always creates a type in `public` schema.

## API proposal:
- `options.schema = '<schema name>'` - use specified schema name;
- `options.schema = true` -  use schema from `withSchema` expression (for backward compatibility if needed);

### Example 1: `options.schema = '<schema name>'` 

```javascript
knex
      .schemaBuilder()
      .withSchema('test')
      .table('users', function(table) {
        table
          .enu('foo', ['bar', 'baz'], {
            useNative: true,
            enumName: 'foo_bar',
            schema: 'test_2',
          })
      })
      .toSQL();
```

Outputs:
```sql
-- ...
create type "test_2"."foo_bar" as enum ('bar', 'baz');
alter table "test"."users" add column "foo" "test_2"."foo_bar";
-- ...
```

### Example 2: `options.schema = true`

```javascript
knex
      .schemaBuilder()
      .withSchema('test')
      .table('users', function(table) {
        table
          .enu('foo', ['bar', 'baz'], {
            useNative: true,
            enumName: 'foo_bar',
            schema: true,
          })
      })
      .toSQL();
```

Outputs:
```sql
-- ...
create type "test"."foo_bar" as enum ('bar', 'baz');
alter table "test"."users" add column "foo" "test"."foo_bar";
-- ...
```

### CODE REVIEW

**Comment by Saka7** [comment]
Some integration test for `oracledb` have been failed, it doesn't look related to changes added in the PR. Can somebody take a look, please?

**Comment by Saka7** [comment]
Another topic: please let me know if we need to keep backward compatibility for native enum (always create enum in the `public` schema). If no, we could remove this ugly `schema: true` options and always use specified schema from `withSchema` expression.

**Comment by kibertoad** [comment]
@Saka7 You can pull latest changes from master to fix Oracle failures. Let me read the proposal and the PR in more details and I'll get back to you on it :)

**Comment by Saka7** [comment]
@kibertoad Did you get a chance to look at this?

**Comment by kibertoad** [comment]
@Saka7 In this particular case I would consider ignoring `.withSchema` a bug and not intended behaviour, so maintaining backwards incompatibility doesn't make sense; if user was explicitly specifying schema, he shouldn't be surprised when it is actually used.

**Comment by kibertoad** [comment]
Fix by itself is great, thank you for your contribution!

**Comment by Saka7** [comment]
@kibertoad ok, so I'll remove `schema: boolean` option. A schema for enum will be used from `.withSchema()`. And it can be overridden by the value from `schema: string` option.

**Comment by kibertoad** [comment]
@Saka7 Do you see benefit from option.schema? Isn't it redundant and inconsistent with other operations? What are th euse-cases for it?

**Comment by Saka7** [comment]
@kibertoad In case somebody by some reason needs to create enum in different schema than the table. But, I guess it's a very rare case, so we might remove `schema` option at all.

**Comment by kibertoad** [comment]
@Saka7 Then we would need to add same for all operations :)

**Comment by Saka7** [comment]
@kibertoad ok, I'll remove `schema` option.

**Comment by kibertoad** [comment]
Thank you!

**Comment by Saka7** [comment]
@kibertoad thank you for the review!

**Comment by ivanovych666** [comment]
Sorry, but, previously we had a problem that for ENUM we can't use any schema except "public" and now we have a problem that we can't use existing types from other schemas or even from "public" schema. This is ridiculous. Maybe creating new tables in one schema and creating new types in another is not well used, but how to create a table with ENUM column where we want to use existing TYPE from a different schema? Please don't forget that we have the "existingType" option and add the option to manually define the schema name back.

**Comment by kibertoad** [comment]
@ivanovych666 That is a valid case, however, I'm not sure if having options.schema is the best solution for that, as if it would be affecting both source and target enum, you still won't be able to use enums from one schema inside another schema. Can't you just append `${schemaName}.` to source enum manually right now?
I'm OK with adding `existingTypeSchema` in a new PR since that provides an explicit way to achieve this specific goal, though. Feel free to submit one.

**Comment by ivanovych666** [comment]
@kibertoad I have created a simple solution, please check here https://github.com/tgriesser/knex/pull/3413

**Pull request merged**
