### PR TITLE
Add syntactic sugar - andWhereBetween and andWhereNotBetween

### PR DESCRIPTION
**Pull request by rfink**
Addresses issue #1131

### CODE REVIEW

**Comment by wubzz** [comment]
@rfink Hey, sorry this PR was left hanging for so long. I'm fine with merging this. Would you mind solving the conflicts here?

**Comment by rfink** [comment]
Sure, merged in and awaiting new tests.

**Comment by wubzz** [comment]
Brilliant. Thanks!

**Comment by rfink** [comment]
Thanks!

**Pull request merged**
